FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app

WORKDIR /app/app

CMD ["celery", "-A", "celery_app", "worker", "-Q", "audio.transcribe,text.summarize", "--concurrency=1", "--loglevel=info"]