<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\spa\scripts\alert.js" />
    <Content Remove="wwwroot\spa\scripts\crudEnumerator.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shered\Shered.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\APP gravação.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\spa\scripts\main.js">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\spa\scripts\components\NovaPasta\" />
    <Folder Include="wwwroot\spa\style\" />
  </ItemGroup>

</Project>
