name: {{COMPOSE_PROJECT_NAME}}

services:
  {{APPLICATION_SLUG}}-front:
    build:
      context: ../../..
      dockerfile: infra/{{APPLICATION_NAME}}/DockerCompose/front/Dockerfile
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:8080"
      ASPNETCORE_ENVIRONMENT: "Production"
    expose:
      - "8080"
    restart: unless-stopped
    networks:
      - yeshua-net

  {{APPLICATION_SLUG}}-api:
    build:
      context: ../../..
      dockerfile: infra/{{APPLICATION_NAME}}/DockerCompose/api/Dockerfile
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:7214"
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__Default: "Server=sqlserver,1433;Database={{DATABASE_NAME}};User Id=sa;Password={{SA_PASSWORD}};TrustServerCertificate=True;"
      Redis__Host: redis
      MYCONFIG__READCONECTIONSTRING: "Server=sqlserver,1433;Database={{DATABASE_NAME}};User Id=sa;Password={{SA_PASSWORD}};TrustServerCertificate=True;"
      MYCONFIG__WRITECONECTIONSTRING: "Server=sqlserver,1433;Database={{DATABASE_NAME}};User Id=sa;Password={{SA_PASSWORD}};TrustServerCertificate=True;"
    expose:
      - "7214"
    restart: unless-stopped
    networks:
      - yeshua-net

  {{APPLICATION_SLUG}}-worker:
    build:
      context: ../../..
      dockerfile: infra/{{APPLICATION_NAME}}/DockerCompose/worker/Dockerfile
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:7215"
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__Default: "Server=sqlserver,1433;Database={{DATABASE_NAME}};User Id=sa;Password={{SA_PASSWORD}};TrustServerCertificate=True;"
      Redis__Host: redis
      MYCONFIG__READCONECTIONSTRING: "Server=sqlserver,1433;Database={{DATABASE_NAME}};User Id=sa;Password={{SA_PASSWORD}};TrustServerCertificate=True;"
      MYCONFIG__WRITECONECTIONSTRING: "Server=sqlserver,1433;Database={{DATABASE_NAME}};User Id=sa;Password={{SA_PASSWORD}};TrustServerCertificate=True;"
      RabbitMq__HostName: rabbitmq
      RabbitMq__Port: 5672
      RabbitMq__Username: "{{RABBITMQ_USER}}"
      RabbitMq__Password: "{{RABBITMQ_PASSWORD}}"
      RabbitMq__VirtualHost: /
    expose:
      - "7215"
    restart: unless-stopped
    networks:
      - yeshua-net

  {{APPLICATION_SLUG}}-migration:
    build:
      context: ../../..
      dockerfile: infra/{{APPLICATION_NAME}}/DockerCompose/migration/Dockerfile
    environment:
      ConnectionStrings__Default: "Server=sqlserver,1433;Database={{DATABASE_NAME}};User Id=sa;Password={{SA_PASSWORD}};TrustServerCertificate=True;"
      MYCONFIG__READCONECTIONSTRING: "Server=sqlserver,1433;Database={{DATABASE_NAME}};User Id=sa;Password={{SA_PASSWORD}};TrustServerCertificate=True;"
      MYCONFIG__WRITECONECTIONSTRING: "Server=sqlserver,1433;Database={{DATABASE_NAME}};User Id=sa;Password={{SA_PASSWORD}};TrustServerCertificate=True;"
    restart: "no"
    networks:
      - yeshua-net

networks:
  yeshua-net:
    external: true
    name: yeshua-net
