upstream front_pool {
    least_conn;
    server front:8080;
}

upstream api_pool {
    least_conn;
    server api:7214;
}

upstream worker_pool {
    least_conn;
    server worker:7215;
}


server {
    listen 80;


    



    # =========================
    # API (Docker)
    # =========================
    location /yapi/ {
        proxy_pass http://api_pool;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

    }

    # =========================
    # FRONT (load balanced)
    # =========================
    location / {
        proxy_pass http://front_pool;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }


    # =========================
    # WORKER (Docker)
    # =========================
    location /yworker/ {
        proxy_pass http://worker_pool;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    
}

