<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Prompts\FrontEndCode.txt" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Prompts\FrontEndCode.txt" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shered\Shered.csproj" />
  </ItemGroup>

</Project>
