<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Dominio\CodeGeneration\Templates\Command\NameCrudCommand.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Principios e objetos de arquitetura.txt" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Principios e objetos de arquitetura.txt">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Dominio\CodeGeneration\Templates\Command\NameCrudCommand.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.35" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.0.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Infra\SqlFactory.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Dominio\CodeGeneration\Model\" />
  </ItemGroup>

</Project>
