// <yeshua>
// artifact: GENERATED_REGENERABLE
// createdBy: DSL
// ownership: ENGINE
// editable: false
// regeneration: REPLACE
// sourceOfTruth: DSL_OR_ENGINE_TEMPLATE
// generator: Dominio.Schemas.CQRS.SourceCodeAplicationRepositoryInterfacesReadMigration
// </yeshua>

using Repositorio.Outputs;
using RepositoryInterfaces.Patterns.Command;
using RepositoryInterfaces.Patterns.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace IRepository.Read
{
    public partial interface ITargetProdutoReadRepository
    {
        public DataPagination<TargetProdutoDTO> getTargetProduto(ICommandRead command );
        public IEnumerable<TargetProdutoMOV_IDDTO> getTargetProdutoReadFKMOV_ID(object command );
        public IEnumerable<TargetProdutoORD_IDDTO> getTargetProdutoReadFKORD_ID(object command );
        public IEnumerable<TargetProdutoUNI_IDDTO> getTargetProdutoReadFKUNI_ID(object command );
        public IEnumerable<TargetProdutoTURM_IDDTO> getTargetProdutoReadFKTURM_ID(object command );
        public IEnumerable<TargetProdutoTURN_IDDTO> getTargetProdutoReadFKTURN_ID(object command );
        public IEnumerable<TargetProdutoUSE_IDDTO> getTargetProdutoReadFKUSE_ID(object command );
        public IEnumerable<TargetProdutoOCO_ID_PERFORMANCEDTO> getTargetProdutoReadFKOCO_ID_PERFORMANCE(object command );
        public IEnumerable<TargetProdutoTenantIDDTO> getTargetProdutoReadFKTenantID(object command );
        public IEnumerable<TargetProdutoUserIdDTO> getTargetProdutoReadFKUserId(object command );
        public bool ExistsByTAR_ID(int value );
        public bool ExistsByMOV_ID(int value );
        public bool ExistsByORD_ID(string value );
        public bool ExistsByPRO_ID(string value );
        public bool ExistsByMAQ_ID(string value );
        public bool ExistsByUNI_ID(string value );
        public bool ExistsByTURM_ID(string value );
        public bool ExistsByTURN_ID(string value );
        public bool ExistsByUSE_ID(int value );
        public bool ExistsByTAR_DIA_TURMA(string value );
        public bool ExistsByTAR_META_PERFORMANCE(Decimal value );
        public bool ExistsByTAR_REALIZADO_PERFORMANCE(Decimal value );
        public bool ExistsByTAR_PERCENTUAL_REALIZADO_PERFORMANCE(Decimal value );
        public bool ExistsByTAR_PROXIMA_META_PERFORMANCE(Decimal value );
        public bool ExistsByTAR_META_TEMPO_SETUP(Decimal value );
        public bool ExistsByTAR_REALIZADO_TEMPO_SETUP(Decimal value );
        public bool ExistsByTAR_PROXIMA_META_TEMPO_SETUP(Decimal value );
        public bool ExistsByTAR_META_TEMPO_SETUP_AJUSTE(Decimal value );
        public bool ExistsByTAR_REALIZADO_TEMPO_SETUP_AJUSTE(Decimal value );
        public bool ExistsByTAR_PROXIMA_META_TEMPO_SETUP_AJUSTE(Decimal value );
        public bool ExistsByOCO_ID_PERFORMANCE(string value );
        public bool ExistsByTAR_OBS_PERFORMANCE(string value );
        public bool ExistsByOCO_ID_SETUP(string value );
        public bool ExistsByTAR_OBS_SETUP(string value );
        public bool ExistsByOCO_ID_SETUPA(string value );
        public bool ExistsByTAR_OBS_SETUPA(string value );
        public bool ExistsByTAR_TIPO_FEEDBACK_PERFORMANCE(string value );
        public bool ExistsByTAR_TIPO_FEEDBACK_SETUP(string value );
        public bool ExistsByTAR_TIPO_FEEDBACK_SETUP_AJUSTE(string value );
        public bool ExistsByTAR_QTD_SETUP_AJUSTE(Decimal value );
        public bool ExistsByTAR_QTD(Decimal value );
        public bool ExistsByTAR_PARAMETRO_TIME_WORK_STOP_MACHINE(int value );
        public bool ExistsByTAR_PARAMETRO_TEMPO_QUEBRA_DE_LOTE(int value );
        public bool ExistsByROT_SEQ_TRANFORMACAO(int value );
        public bool ExistsByFPR_SEQ_REPETICAO(int value );
        public bool ExistsByTAR_PERFORMANCE_MAX_VERDE(Decimal value );
        public bool ExistsByTAR_PERFORMANCE_MIN_VERDE(Decimal value );
        public bool ExistsByTAR_SETUP_MAX_VERDE(Decimal value );
        public bool ExistsByTAR_SETUP_MIN_VERDE(Decimal value );
        public bool ExistsByTAR_SETUPA_MAX_VERDE(Decimal value );
        public bool ExistsByTAR_SETUPA_MIN_VERDE(Decimal value );
        public bool ExistsByTAR_PERFORMANCE_MIN_AMARELO(Decimal value );
        public bool ExistsByTAR_SETUP_MAX_AMARELO(Decimal value );
        public bool ExistsByTAR_SETUPA_MAX_AMARELO(Decimal value );
        public bool ExistsByTAR_OBS_OP_PARCIAL(string value );
        public bool ExistsByTAR_OCO_ID_OP_PARCIAL(string value );
        public bool ExistsByTAR_COR_PERFORMANCE(string value );
        public bool ExistsByTAR_COR_SETUP_GERAL(string value );
        public bool ExistsByTAR_COR_SETUP(string value );
        public bool ExistsByTAR_COR_SETUPA(string value );
        public bool ExistsByTAR_DIA_TURMA_D(DateTime value );
        public bool ExistsByFEE_QTD_PECAS_POR_PULSO(Decimal value );
        public bool ExistsByTAR_QTD_PERDAS(Decimal value );
        public bool ExistsByTAR_DATA_INICIAL(DateTime value );
        public bool ExistsByTAR_DATA_FINAL(DateTime value );
        public bool ExistsByTAR_APROVADO(string value );
        public bool ExistsByTAR_TEMPO_PRODUZINDO(int value );
        public bool ExistsByTenantID(int value );
        public bool ExistsByDeleted(bool value );
        public bool ExistsByChanged(DateTime value );
        public bool ExistsByUserId(int value );
        public TargetProdutoDTO FirstByTAR_ID(int value );
        public TargetProdutoDTO FirstByMOV_ID(int value );
        public TargetProdutoDTO FirstByORD_ID(string value );
        public TargetProdutoDTO FirstByPRO_ID(string value );
        public TargetProdutoDTO FirstByMAQ_ID(string value );
        public TargetProdutoDTO FirstByUNI_ID(string value );
        public TargetProdutoDTO FirstByTURM_ID(string value );
        public TargetProdutoDTO FirstByTURN_ID(string value );
        public TargetProdutoDTO FirstByUSE_ID(int value );
        public TargetProdutoDTO FirstByTAR_DIA_TURMA(string value );
        public TargetProdutoDTO FirstByTAR_META_PERFORMANCE(Decimal value );
        public TargetProdutoDTO FirstByTAR_REALIZADO_PERFORMANCE(Decimal value );
        public TargetProdutoDTO FirstByTAR_PERCENTUAL_REALIZADO_PERFORMANCE(Decimal value );
        public TargetProdutoDTO FirstByTAR_PROXIMA_META_PERFORMANCE(Decimal value );
        public TargetProdutoDTO FirstByTAR_META_TEMPO_SETUP(Decimal value );
        public TargetProdutoDTO FirstByTAR_REALIZADO_TEMPO_SETUP(Decimal value );
        public TargetProdutoDTO FirstByTAR_PROXIMA_META_TEMPO_SETUP(Decimal value );
        public TargetProdutoDTO FirstByTAR_META_TEMPO_SETUP_AJUSTE(Decimal value );
        public TargetProdutoDTO FirstByTAR_REALIZADO_TEMPO_SETUP_AJUSTE(Decimal value );
        public TargetProdutoDTO FirstByTAR_PROXIMA_META_TEMPO_SETUP_AJUSTE(Decimal value );
        public TargetProdutoDTO FirstByOCO_ID_PERFORMANCE(string value );
        public TargetProdutoDTO FirstByTAR_OBS_PERFORMANCE(string value );
        public TargetProdutoDTO FirstByOCO_ID_SETUP(string value );
        public TargetProdutoDTO FirstByTAR_OBS_SETUP(string value );
        public TargetProdutoDTO FirstByOCO_ID_SETUPA(string value );
        public TargetProdutoDTO FirstByTAR_OBS_SETUPA(string value );
        public TargetProdutoDTO FirstByTAR_TIPO_FEEDBACK_PERFORMANCE(string value );
        public TargetProdutoDTO FirstByTAR_TIPO_FEEDBACK_SETUP(string value );
        public TargetProdutoDTO FirstByTAR_TIPO_FEEDBACK_SETUP_AJUSTE(string value );
        public TargetProdutoDTO FirstByTAR_QTD_SETUP_AJUSTE(Decimal value );
        public TargetProdutoDTO FirstByTAR_QTD(Decimal value );
        public TargetProdutoDTO FirstByTAR_PARAMETRO_TIME_WORK_STOP_MACHINE(int value );
        public TargetProdutoDTO FirstByTAR_PARAMETRO_TEMPO_QUEBRA_DE_LOTE(int value );
        public TargetProdutoDTO FirstByROT_SEQ_TRANFORMACAO(int value );
        public TargetProdutoDTO FirstByFPR_SEQ_REPETICAO(int value );
        public TargetProdutoDTO FirstByTAR_PERFORMANCE_MAX_VERDE(Decimal value );
        public TargetProdutoDTO FirstByTAR_PERFORMANCE_MIN_VERDE(Decimal value );
        public TargetProdutoDTO FirstByTAR_SETUP_MAX_VERDE(Decimal value );
        public TargetProdutoDTO FirstByTAR_SETUP_MIN_VERDE(Decimal value );
        public TargetProdutoDTO FirstByTAR_SETUPA_MAX_VERDE(Decimal value );
        public TargetProdutoDTO FirstByTAR_SETUPA_MIN_VERDE(Decimal value );
        public TargetProdutoDTO FirstByTAR_PERFORMANCE_MIN_AMARELO(Decimal value );
        public TargetProdutoDTO FirstByTAR_SETUP_MAX_AMARELO(Decimal value );
        public TargetProdutoDTO FirstByTAR_SETUPA_MAX_AMARELO(Decimal value );
        public TargetProdutoDTO FirstByTAR_OBS_OP_PARCIAL(string value );
        public TargetProdutoDTO FirstByTAR_OCO_ID_OP_PARCIAL(string value );
        public TargetProdutoDTO FirstByTAR_COR_PERFORMANCE(string value );
        public TargetProdutoDTO FirstByTAR_COR_SETUP_GERAL(string value );
        public TargetProdutoDTO FirstByTAR_COR_SETUP(string value );
        public TargetProdutoDTO FirstByTAR_COR_SETUPA(string value );
        public TargetProdutoDTO FirstByTAR_DIA_TURMA_D(DateTime value );
        public TargetProdutoDTO FirstByFEE_QTD_PECAS_POR_PULSO(Decimal value );
        public TargetProdutoDTO FirstByTAR_QTD_PERDAS(Decimal value );
        public TargetProdutoDTO FirstByTAR_DATA_INICIAL(DateTime value );
        public TargetProdutoDTO FirstByTAR_DATA_FINAL(DateTime value );
        public TargetProdutoDTO FirstByTAR_APROVADO(string value );
        public TargetProdutoDTO FirstByTAR_TEMPO_PRODUZINDO(int value );
        public TargetProdutoDTO FirstByTenantID(int value );
        public TargetProdutoDTO FirstByDeleted(bool value );
        public TargetProdutoDTO FirstByChanged(DateTime value );
        public TargetProdutoDTO FirstByUserId(int value );
        public IEnumerable<TargetProdutoDTO> GetAllByTAR_ID(int value );
        public IEnumerable<TargetProdutoDTO> GetAllByMOV_ID(int value );
        public IEnumerable<TargetProdutoDTO> GetAllByORD_ID(string value );
        public IEnumerable<TargetProdutoDTO> GetAllByPRO_ID(string value );
        public IEnumerable<TargetProdutoDTO> GetAllByMAQ_ID(string value );
        public IEnumerable<TargetProdutoDTO> GetAllByUNI_ID(string value );
        public IEnumerable<TargetProdutoDTO> GetAllByTURM_ID(string value );
        public IEnumerable<TargetProdutoDTO> GetAllByTURN_ID(string value );
        public IEnumerable<TargetProdutoDTO> GetAllByUSE_ID(int value );
        public IEnumerable<TargetProdutoDTO> GetAllByTAR_DIA_TURMA(string value );
        public IEnumerable<TargetProdutoDTO> GetAllByTAR_META_PERFORMANCE(Decimal value );
        public IEnumerable<TargetProdutoDTO> GetAllByTAR_REALIZADO_PERFORMANCE(Decimal value );
        public IEnumerable<TargetProdutoDTO> GetAllByTAR_PERCENTUAL_REALIZADO_PERFORMANCE(Decimal value );
        public IEnumerable<TargetProdutoDTO> GetAllByTAR_PROXIMA_META_PERFORMANCE(Decimal value );
        public IEnumerable<TargetProdutoDTO> GetAllByTAR_META_TEMPO_SETUP(Decimal value );
        public IEnumerable<TargetProdutoDTO> GetAllByTAR_REALIZADO_TEMPO_SETUP(Decimal value );
        public IEnumerable<TargetProdutoDTO> GetAllByTAR_PROXIMA_META_TEMPO_SETUP(Decimal value );
        public IEnumerable<TargetProdutoDTO> GetAllByTAR_META_TEMPO_SETUP_AJUSTE(Decimal value );
        public IEnumerable<TargetProdutoDTO> GetAllByTAR_REALIZADO_TEMPO_SETUP_AJUSTE(Decimal value );
        public IEnumerable<TargetProdutoDTO> GetAllByTAR_PROXIMA_META_TEMPO_SETUP_AJUSTE(Decimal value );
        public IEnumerable<TargetProdutoDTO> GetAllByOCO_ID_PERFORMANCE(string value );
        public IEnumerable<TargetProdutoDTO> GetAllByTAR_OBS_PERFORMANCE(string value );
        public IEnumerable<TargetProdutoDTO> GetAllByOCO_ID_SETUP(string value );
        public IEnumerable<TargetProdutoDTO> GetAllByTAR_OBS_SETUP(string value );
        public IEnumerable<TargetProdutoDTO> GetAllByOCO_ID_SETUPA(string value );
        public IEnumerable<TargetProdutoDTO> GetAllByTAR_OBS_SETUPA(string value );
        public IEnumerable<TargetProdutoDTO> GetAllByTAR_TIPO_FEEDBACK_PERFORMANCE(string value );
        public IEnumerable<TargetProdutoDTO> GetAllByTAR_TIPO_FEEDBACK_SETUP(string value );
        public IEnumerable<TargetProdutoDTO> GetAllByTAR_TIPO_FEEDBACK_SETUP_AJUSTE(string value );
        public IEnumerable<TargetProdutoDTO> GetAllByTAR_QTD_SETUP_AJUSTE(Decimal value );
        public IEnumerable<TargetProdutoDTO> GetAllByTAR_QTD(Decimal value );
        public IEnumerable<TargetProdutoDTO> GetAllByTAR_PARAMETRO_TIME_WORK_STOP_MACHINE(int value );
        public IEnumerable<TargetProdutoDTO> GetAllByTAR_PARAMETRO_TEMPO_QUEBRA_DE_LOTE(int value );
        public IEnumerable<TargetProdutoDTO> GetAllByROT_SEQ_TRANFORMACAO(int value );
        public IEnumerable<TargetProdutoDTO> GetAllByFPR_SEQ_REPETICAO(int value );
        public IEnumerable<TargetProdutoDTO> GetAllByTAR_PERFORMANCE_MAX_VERDE(Decimal value );
        public IEnumerable<TargetProdutoDTO> GetAllByTAR_PERFORMANCE_MIN_VERDE(Decimal value );
        public IEnumerable<TargetProdutoDTO> GetAllByTAR_SETUP_MAX_VERDE(Decimal value );
        public IEnumerable<TargetProdutoDTO> GetAllByTAR_SETUP_MIN_VERDE(Decimal value );
        public IEnumerable<TargetProdutoDTO> GetAllByTAR_SETUPA_MAX_VERDE(Decimal value );
        public IEnumerable<TargetProdutoDTO> GetAllByTAR_SETUPA_MIN_VERDE(Decimal value );
        public IEnumerable<TargetProdutoDTO> GetAllByTAR_PERFORMANCE_MIN_AMARELO(Decimal value );
        public IEnumerable<TargetProdutoDTO> GetAllByTAR_SETUP_MAX_AMARELO(Decimal value );
        public IEnumerable<TargetProdutoDTO> GetAllByTAR_SETUPA_MAX_AMARELO(Decimal value );
        public IEnumerable<TargetProdutoDTO> GetAllByTAR_OBS_OP_PARCIAL(string value );
        public IEnumerable<TargetProdutoDTO> GetAllByTAR_OCO_ID_OP_PARCIAL(string value );
        public IEnumerable<TargetProdutoDTO> GetAllByTAR_COR_PERFORMANCE(string value );
        public IEnumerable<TargetProdutoDTO> GetAllByTAR_COR_SETUP_GERAL(string value );
        public IEnumerable<TargetProdutoDTO> GetAllByTAR_COR_SETUP(string value );
        public IEnumerable<TargetProdutoDTO> GetAllByTAR_COR_SETUPA(string value );
        public IEnumerable<TargetProdutoDTO> GetAllByTAR_DIA_TURMA_D(DateTime value );
        public IEnumerable<TargetProdutoDTO> GetAllByFEE_QTD_PECAS_POR_PULSO(Decimal value );
        public IEnumerable<TargetProdutoDTO> GetAllByTAR_QTD_PERDAS(Decimal value );
        public IEnumerable<TargetProdutoDTO> GetAllByTAR_DATA_INICIAL(DateTime value );
        public IEnumerable<TargetProdutoDTO> GetAllByTAR_DATA_FINAL(DateTime value );
        public IEnumerable<TargetProdutoDTO> GetAllByTAR_APROVADO(string value );
        public IEnumerable<TargetProdutoDTO> GetAllByTAR_TEMPO_PRODUZINDO(int value );
        public IEnumerable<TargetProdutoDTO> GetAllByTenantID(int value );
        public IEnumerable<TargetProdutoDTO> GetAllByDeleted(bool value );
        public IEnumerable<TargetProdutoDTO> GetAllByChanged(DateTime value );
        public IEnumerable<TargetProdutoDTO> GetAllByUserId(int value );
    }
}
//Dominio.Schemas.CQRS.SourceCodeAplicationRepositoryInterfacesReadMigration