<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BuildInParallel>false</BuildInParallel>
  </PropertyGroup>

  <ItemGroup>
                    <ProjectReference Include="..\Yeshua.CQRS.Application.Command\Yeshua.CQRS.Application.Command.csproj" />
                    <ProjectReference Include="..\..\Domain\Yeshua.Fiscal.CQRS.Domain\Yeshua.Fiscal.CQRS.Domain.csproj" />
                    <ProjectReference Include="..\Yeshua.Fiscal.CQRS.Application.RepositoryInterfaces\Yeshua.Fiscal.CQRS.Application.RepositoryInterfaces.csproj" />
                  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Security.Cryptography.Xml" Version="8.0.4" />
  </ItemGroup>

</Project>
