<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Properties\n.conf" />
    <None Remove="Properties\nginx.conf" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Yeshua.CQRS.Infrastructure.Shared\Yeshua.CQRS.Infrastructure.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromPublish>true</ExcludeFromPublish>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Content Update="wwwroot\spa\environments.js">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromPublish>true</ExcludeFromPublish>
    </Content>
  </ItemGroup>

</Project>
