using Repositorio.Outputs;
using RepositoryInterfaces.Patterns.Command;
using RepositoryInterfaces.Patterns.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace IRepository.Read
{
    public interface ISesoesReadRepository
    {
        public DataPagination<SesoesDTO> getSesoes(ICommandRead command );
        public IEnumerable<SesoesPacienteIdDTO> getSesoesReadFKPacienteId(object command );
        public IEnumerable<SesoesMovimentacaoFinanceiraIdDTO> getSesoesReadFKMovimentacaoFinanceiraId(object command );
        public IEnumerable<SesoesServicoIdDTO> getSesoesReadFKServicoId(object command );
        public IEnumerable<SesoesProfissionalIdDTO> getSesoesReadFKProfissionalId(object command );
        public IEnumerable<SesoesTenantIDDTO> getSesoesReadFKTenantID(object command );
        public IEnumerable<SesoesUserIdDTO> getSesoesReadFKUserId(object command );
        public bool ExistsByPacienteId(int value );
        public bool ExistsByDataInicio(DateTime value );
        public bool ExistsByDataFim(DateTime value );
        public bool ExistsByStatus(int value );
        public bool ExistsByMovimentacaoFinanceiraId(int value );
        public bool ExistsByProntuario(string value );
        public bool ExistsByQueixaPrincipal(string value );
        public bool ExistsByRegistroDocumental(string value );
        public bool ExistsBySintomasRelatados(string value );
        public bool ExistsByMudancasDesdeUltimaSessaao(int value );
        public bool ExistsByComportamentoObservado(string value );
        public bool ExistsByEstadoEmocionalGeral(string value );
        public bool ExistsByDiscursoPensamentos(string value );
        public bool ExistsByUsoMedicacao(string value );
        public bool ExistsByTecnicasUtilizadas(string value );
        public bool ExistsByQuestionamentosReflexoesAbordadas(string value );
        public bool ExistsByExerciciosTarefasSugeridas(string value );
        public bool ExistsByDiagnoosticoHipoteseDiagnoostica(string value );
        public bool ExistsByObjetivosCurtoPrazo(string value );
        public bool ExistsByObjetivosLongoPrazo(string value );
        public bool ExistsByFrequenciaSugeridaSessooes(string value );
        public bool ExistsByEncaminhamentoOutrosProfissionais(string value );
        public bool ExistsByInformacoesRelevantesFuturasConsultas(string value );
        public bool ExistsByFeedbackPacienteSobreProcessoTerapeeutico(string value );
        public bool ExistsById(int value );
        public bool ExistsByServicoId(int value );
        public bool ExistsByProfissionalId(int value );
        public bool ExistsByTenantID(int value );
        public bool ExistsByDeleted(bool value );
        public bool ExistsByChanged(DateTime value );
        public bool ExistsByUserId(int value );
        public SesoesDTO FirstByPacienteId(int value );
        public SesoesDTO FirstByDataInicio(DateTime value );
        public SesoesDTO FirstByDataFim(DateTime value );
        public SesoesDTO FirstByStatus(int value );
        public SesoesDTO FirstByMovimentacaoFinanceiraId(int value );
        public SesoesDTO FirstByProntuario(string value );
        public SesoesDTO FirstByQueixaPrincipal(string value );
        public SesoesDTO FirstByRegistroDocumental(string value );
        public SesoesDTO FirstBySintomasRelatados(string value );
        public SesoesDTO FirstByMudancasDesdeUltimaSessaao(int value );
        public SesoesDTO FirstByComportamentoObservado(string value );
        public SesoesDTO FirstByEstadoEmocionalGeral(string value );
        public SesoesDTO FirstByDiscursoPensamentos(string value );
        public SesoesDTO FirstByUsoMedicacao(string value );
        public SesoesDTO FirstByTecnicasUtilizadas(string value );
        public SesoesDTO FirstByQuestionamentosReflexoesAbordadas(string value );
        public SesoesDTO FirstByExerciciosTarefasSugeridas(string value );
        public SesoesDTO FirstByDiagnoosticoHipoteseDiagnoostica(string value );
        public SesoesDTO FirstByObjetivosCurtoPrazo(string value );
        public SesoesDTO FirstByObjetivosLongoPrazo(string value );
        public SesoesDTO FirstByFrequenciaSugeridaSessooes(string value );
        public SesoesDTO FirstByEncaminhamentoOutrosProfissionais(string value );
        public SesoesDTO FirstByInformacoesRelevantesFuturasConsultas(string value );
        public SesoesDTO FirstByFeedbackPacienteSobreProcessoTerapeeutico(string value );
        public SesoesDTO FirstById(int value );
        public SesoesDTO FirstByServicoId(int value );
        public SesoesDTO FirstByProfissionalId(int value );
        public SesoesDTO FirstByTenantID(int value );
        public SesoesDTO FirstByDeleted(bool value );
        public SesoesDTO FirstByChanged(DateTime value );
        public SesoesDTO FirstByUserId(int value );
        public IEnumerable<SesoesDTO> GetAllByPacienteId(int value );
        public IEnumerable<SesoesDTO> GetAllByDataInicio(DateTime value );
        public IEnumerable<SesoesDTO> GetAllByDataFim(DateTime value );
        public IEnumerable<SesoesDTO> GetAllByStatus(int value );
        public IEnumerable<SesoesDTO> GetAllByMovimentacaoFinanceiraId(int value );
        public IEnumerable<SesoesDTO> GetAllByProntuario(string value );
        public IEnumerable<SesoesDTO> GetAllByQueixaPrincipal(string value );
        public IEnumerable<SesoesDTO> GetAllByRegistroDocumental(string value );
        public IEnumerable<SesoesDTO> GetAllBySintomasRelatados(string value );
        public IEnumerable<SesoesDTO> GetAllByMudancasDesdeUltimaSessaao(int value );
        public IEnumerable<SesoesDTO> GetAllByComportamentoObservado(string value );
        public IEnumerable<SesoesDTO> GetAllByEstadoEmocionalGeral(string value );
        public IEnumerable<SesoesDTO> GetAllByDiscursoPensamentos(string value );
        public IEnumerable<SesoesDTO> GetAllByUsoMedicacao(string value );
        public IEnumerable<SesoesDTO> GetAllByTecnicasUtilizadas(string value );
        public IEnumerable<SesoesDTO> GetAllByQuestionamentosReflexoesAbordadas(string value );
        public IEnumerable<SesoesDTO> GetAllByExerciciosTarefasSugeridas(string value );
        public IEnumerable<SesoesDTO> GetAllByDiagnoosticoHipoteseDiagnoostica(string value );
        public IEnumerable<SesoesDTO> GetAllByObjetivosCurtoPrazo(string value );
        public IEnumerable<SesoesDTO> GetAllByObjetivosLongoPrazo(string value );
        public IEnumerable<SesoesDTO> GetAllByFrequenciaSugeridaSessooes(string value );
        public IEnumerable<SesoesDTO> GetAllByEncaminhamentoOutrosProfissionais(string value );
        public IEnumerable<SesoesDTO> GetAllByInformacoesRelevantesFuturasConsultas(string value );
        public IEnumerable<SesoesDTO> GetAllByFeedbackPacienteSobreProcessoTerapeeutico(string value );
        public IEnumerable<SesoesDTO> GetAllById(int value );
        public IEnumerable<SesoesDTO> GetAllByServicoId(int value );
        public IEnumerable<SesoesDTO> GetAllByProfissionalId(int value );
        public IEnumerable<SesoesDTO> GetAllByTenantID(int value );
        public IEnumerable<SesoesDTO> GetAllByDeleted(bool value );
        public IEnumerable<SesoesDTO> GetAllByChanged(DateTime value );
        public IEnumerable<SesoesDTO> GetAllByUserId(int value );
        public DataPagination<SesoesStandardDTO> GetSesoesHoje(ICommandRead command );
        public DataPagination<SesoesStandardDTO> GetSesoesSemana(ICommandRead command );
        public DataPagination<SesoesStandardDTO> GetSesoesMes(ICommandRead command );
        public DataPagination<SesoesStandardDTO> GetSesoesGeral(ICommandRead command );
    }
}
//Dominio.Schemas.CQRS.SourceCodeAplicationRepositoryInterfacesReadMigration