upstream clinica_front_pool {
    least_conn;
    server clinica-front:8080;
}

upstream clinica_api_pool {
    least_conn;
    server clinica-api:7214;
}

upstream clinica_worker_pool {
    least_conn;
    server clinica-worker:7215;
}

upstream operational_intelligence_api_pool {
    least_conn;
    server operational-intelligence-api:5728;
}
