upstream central_front_pool {
    least_conn;
    server central-front:8080;
}

upstream central_api_pool {
    least_conn;
    server central-api:7214;
}

upstream central_worker_pool {
    least_conn;
    server central-worker:7215;
}

upstream clinica_api_pool {
    least_conn;
    server clinica-api:7214;
}

upstream clinica_worker_pool {
    least_conn;
    server clinica-worker:7215;
}

upstream aps_adm_api_pool {
    least_conn;
    server aps-adm-api:7214;
}

upstream aps_adm_worker_pool {
    least_conn;
    server aps-adm-worker:7215;
}

upstream fiscal_api_pool {
    least_conn;
    server fiscal-api:7214;
}

upstream fiscal_worker_pool {
    least_conn;
    server fiscal-worker:7215;
}

upstream operational_intelligence_api_pool {
    least_conn;
    server operational-intelligence-api:5728;
}
