upstream clinica_front_pool {
    least_conn;
    server clinica-front:8080;
}

upstream clinica_api_pool {
    least_conn;
    server clinica-api:7214;
}

upstream clinica_worker_pool {
    least_conn;
    server clinica-worker:7215;
}

upstream mdfe_front_pool {
    least_conn;
    server fiscal-mdfe-front:8080;
}

upstream mdfe_api_pool {
    least_conn;
    server fiscal-mdfe-api:7214;
}

