<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Yeshua.CQRS.Application.RepositoryInterfaces\Yeshua.CQRS.Application.RepositoryInterfaces.csproj" />
    <ProjectReference Include="..\..\Domain\Yeshua.APS.Cadastros.CQRS.Domain\Yeshua.APS.Cadastros.CQRS.Domain.csproj" />
  </ItemGroup>

</Project>