using System.Text;

internal static class ReferenceSqlWriter
{
    public static async Task WriteAsync(ReferenceIndexModel model, string outputDirectory)
    {
        Directory.CreateDirectory(outputDirectory);

        await File.WriteAllTextAsync(
            Path.Combine(outputDirectory, "00-reference-index-schema.sql"),
            Schema,
            new UTF8Encoding(false));

        await WriteDataAsync(
            model,
            Path.Combine(outputDirectory, "01-reference-index-data.sql"));

        await File.WriteAllTextAsync(
            Path.Combine(outputDirectory, "02-query-field-sources.sql"),
            RenderQuery(FieldQuerySql, model, GetExampleSymbol(model, "PROPERTY", "FIELD")),
            new UTF8Encoding(false));

        await File.WriteAllTextAsync(
            Path.Combine(outputDirectory, "03-query-class-sources.sql"),
            RenderQuery(ClassQuerySql, model, GetExampleSymbol(model, "CLASS")),
            new UTF8Encoding(false));

        await File.WriteAllTextAsync(
            Path.Combine(outputDirectory, "04-query-function-sources.sql"),
            RenderQuery(
                FunctionQuerySql,
                model,
                GetExampleSymbol(model, "METHOD", "CONSTRUCTOR", "ACCESSOR", "LOCAL_FUNCTION", "LAMBDA")),
            new UTF8Encoding(false));
    }

    internal static string Schema => SchemaSql + Environment.NewLine + ExtensionSchemaSql;

    private static string RenderQuery(string template, ReferenceIndexModel model, string exampleSymbol)
    {
        return template
            .Replace("__APPLICATION__", SqlString(model.ApplicationName), StringComparison.Ordinal)
            .Replace("__VERSION__", SqlString(model.Version), StringComparison.Ordinal)
            .Replace("__SYMBOL__", SqlString(exampleSymbol), StringComparison.Ordinal);
    }

    private static string GetExampleSymbol(ReferenceIndexModel model, params string[] kinds)
    {
        var kindPriority = kinds
            .Select((kind, index) => new { kind, index })
            .ToDictionary(item => item.kind, item => item.index, StringComparer.Ordinal);
        var seedProjectIds = model.Projects.Values
            .Where(project => project.IsSeedProject)
            .Select(project => project.ProjectId)
            .ToHashSet();

        return model.Symbols.Values
                   .Where(symbol => kindPriority.ContainsKey(symbol.Kind))
                   .Where(symbol => !symbol.Name.StartsWith('<') &&
                                    !symbol.QualifiedName.StartsWith('<') &&
                                    !symbol.QualifiedName.StartsWith('('))
                   .OrderByDescending(symbol => seedProjectIds.Contains(symbol.ProjectId))
                   .ThenByDescending(symbol => symbol.QualifiedName.Contains(".Entitys.", StringComparison.Ordinal))
                   .ThenBy(symbol => kindPriority[symbol.Kind])
                   .ThenBy(symbol => symbol.QualifiedName, StringComparer.Ordinal)
                   .Select(symbol => symbol.QualifiedName)
                   .FirstOrDefault()
               ?? "REPLACE_WITH_SYMBOL";
    }

    private static async Task WriteDataAsync(ReferenceIndexModel model, string path)
    {
        await using var writer = new StreamWriter(path, false, new UTF8Encoding(false));
        await writer.WriteLineAsync("-- Generated by Yeshua.Engine.AIContextBuilder.");
        await writer.WriteLineAsync("-- Execute 00-reference-index-schema.sql before this script.");
        await writer.WriteLineAsync("SET NOCOUNT ON;");
        await writer.WriteLineAsync("SET XACT_ABORT ON;");
        await writer.WriteLineAsync("BEGIN TRANSACTION;");
        await writer.WriteLineAsync($"DECLARE @ApplicationId UNIQUEIDENTIFIER = {SqlGuid(model.ApplicationId)};");
        await writer.WriteLineAsync($"DECLARE @BuildId UNIQUEIDENTIFIER = {SqlGuid(model.BuildId)};");
        await writer.WriteLineAsync();
        await writer.WriteLineAsync("IF NOT EXISTS (SELECT 1 FROM OI_Applications WHERE ApplicationId = @ApplicationId)");
        await writer.WriteLineAsync($"    INSERT INTO OI_Applications (ApplicationId, Name, SystemType) VALUES (@ApplicationId, {SqlString(model.ApplicationName)}, {SqlString(model.SystemType)});");
        await writer.WriteLineAsync($"ELSE UPDATE OI_Applications SET SystemType = {SqlString(model.SystemType)} WHERE ApplicationId = @ApplicationId;");
        await writer.WriteLineAsync();
        await writer.WriteLineAsync("DELETE FROM OI_FunctionCalls WHERE BuildId = @BuildId;");
        await writer.WriteLineAsync("IF OBJECT_ID(N'OI_TextReferences', N'U') IS NOT NULL DELETE FROM OI_TextReferences WHERE BuildId = @BuildId;");
        await writer.WriteLineAsync("DELETE FROM OI_ClassInstantiations WHERE BuildId = @BuildId;");
        await writer.WriteLineAsync("DELETE FROM OI_FieldReferences WHERE BuildId = @BuildId;");
        await writer.WriteLineAsync("DELETE FROM OI_Declarations WHERE BuildId = @BuildId;");
        await writer.WriteLineAsync("DELETE FROM OI_Symbols WHERE BuildId = @BuildId;");
        await writer.WriteLineAsync("DELETE FROM OI_Files WHERE BuildId = @BuildId;");
        await writer.WriteLineAsync("DELETE FROM OI_Projects WHERE BuildId = @BuildId;");
        await writer.WriteLineAsync("DELETE FROM OI_Builds WHERE BuildId = @BuildId;");
        await writer.WriteLineAsync();
        await writer.WriteLineAsync(
            "INSERT INTO OI_Builds (BuildId, ApplicationId, Version, CommitSha, SourceSolution, GeneratedAtUtc, ManifestHashSha256) VALUES " +
            $"(@BuildId, @ApplicationId, {SqlString(model.Version)}, {SqlString(model.CommitSha)}, " +
            $"{SqlString(model.SourceSolution)}, {SqlDateTime(model.GeneratedAtUtc)}, {SqlString(model.ManifestHashSha256)});");

        await WriteRowsAsync(
            writer,
            "OI_Projects",
            "ProjectId, BuildId, Name, AssemblyName, ProjectPath, SourceDirectory, IsSeedProject",
            model.Projects.Values.OrderBy(row => row.Name),
            row => $"({SqlGuid(row.ProjectId)}, @BuildId, {SqlString(row.Name)}, {SqlString(row.AssemblyName)}, {SqlString(row.ProjectPath)}, {SqlString(row.SourceDirectory)}, {SqlBool(row.IsSeedProject)})");

        await WriteRowsAsync(
            writer,
            "OI_Files",
            "FileId, BuildId, ProjectId, RelativePath, HashSha256, ArtifactKind, SourceRole, Ownership, Editable, SourceOfTruth",
            model.Files.Values.OrderBy(row => row.RelativePath),
            row => $"({SqlGuid(row.FileId)}, @BuildId, {SqlGuid(row.ProjectId)}, {SqlString(row.RelativePath)}, {SqlString(row.HashSha256)}, " +
                   $"{SqlString(row.ArtifactKind)}, {SqlString(row.SourceRole)}, {SqlString(row.Ownership)}, {SqlBool(row.Editable)}, {SqlString(row.SourceOfTruth)})");

        await WriteRowsAsync(
            writer,
            "OI_Symbols",
            "SymbolId, BuildId, ProjectId, ContainingSymbolId, Kind, Name, QualifiedName, SymbolKey",
            model.Symbols.Values.OrderBy(row => row.QualifiedName).ThenBy(row => row.Kind),
            row => $"({SqlGuid(row.SymbolId)}, @BuildId, {SqlGuid(row.ProjectId)}, {SqlGuid(row.ContainingSymbolId)}, " +
                   $"{SqlString(row.Kind)}, {SqlString(row.Name)}, {SqlString(row.QualifiedName)}, {SqlString(row.SymbolKey)})");

        await WriteRowsAsync(
            writer,
            "OI_Declarations",
            "DeclarationId, BuildId, SymbolId, FileId, StartLine, StartColumn, EndLine, EndColumn",
            model.Declarations.Values.OrderBy(row => row.FileId).ThenBy(row => row.StartLine),
            row => $"({SqlGuid(row.DeclarationId)}, @BuildId, {SqlGuid(row.SymbolId)}, {SqlGuid(row.FileId)}, " +
                   $"{row.StartLine}, {row.StartColumn}, {row.EndLine}, {row.EndColumn})");

        await WriteRowsAsync(
            writer,
            "OI_FieldReferences",
            "FieldReferenceId, BuildId, FieldSymbolId, ContainingFunctionId, FileId, AccessKind, Line, ColumnNumber, ResolutionKind",
            model.FieldReferences.Values.OrderBy(row => row.FileId).ThenBy(row => row.Line),
            row => $"({SqlGuid(row.FieldReferenceId)}, @BuildId, {SqlGuid(row.FieldSymbolId)}, {SqlGuid(row.ContainingFunctionId)}, " +
                   $"{SqlGuid(row.FileId)}, {SqlString(row.AccessKind)}, {row.Line}, {row.Column}, {SqlString(row.ResolutionKind)})");

        await WriteRowsAsync(
            writer,
            "OI_ClassInstantiations",
            "InstantiationId, BuildId, ClassSymbolId, ConstructorSymbolId, ContainingFunctionId, FileId, Line, ColumnNumber, ResolutionKind",
            model.ClassInstantiations.Values.OrderBy(row => row.FileId).ThenBy(row => row.Line),
            row => $"({SqlGuid(row.InstantiationId)}, @BuildId, {SqlGuid(row.ClassSymbolId)}, {SqlGuid(row.ConstructorSymbolId)}, " +
                   $"{SqlGuid(row.ContainingFunctionId)}, {SqlGuid(row.FileId)}, {row.Line}, {row.Column}, {SqlString(row.ResolutionKind)})");

        await WriteRowsAsync(
            writer,
            "OI_FunctionCalls",
            "FunctionCallId, BuildId, CallerFunctionId, CalledFunctionId, FileId, Line, ColumnNumber, ResolutionKind",
            model.FunctionCalls.Values.OrderBy(row => row.CallerFunctionId).ThenBy(row => row.CalledFunctionId),
            row => $"({SqlGuid(row.FunctionCallId)}, @BuildId, {SqlGuid(row.CallerFunctionId)}, {SqlGuid(row.CalledFunctionId)}, " +
                   $"{SqlGuid(row.FileId)}, {SqlInt(row.Line)}, {SqlInt(row.Column)}, {SqlString(row.ResolutionKind)})");

        await WriteRowsAsync(
            writer,
            "OI_TextReferences",
            "TextReferenceId, BuildId, FileId, Token, ReferenceKind, Line, ColumnNumber, ContextSnippet",
            model.TextReferences.Values.OrderBy(row => row.FileId).ThenBy(row => row.Line).ThenBy(row => row.Column),
            row => $"({SqlGuid(row.TextReferenceId)}, @BuildId, {SqlGuid(row.FileId)}, {SqlString(row.Token)}, " +
                   $"{SqlString(row.ReferenceKind)}, {row.Line}, {row.Column}, {SqlString(row.ContextSnippet)})");

        await writer.WriteLineAsync();
        await writer.WriteLineAsync("COMMIT TRANSACTION;");
    }

    private static async Task WriteRowsAsync<T>(
        StreamWriter writer,
        string table,
        string columns,
        IEnumerable<T> sourceRows,
        Func<T, string> format)
    {
        const int batchSize = 500;
        var rows = sourceRows.ToArray();

        for (var offset = 0; offset < rows.Length; offset += batchSize)
        {
            var batch = rows.Skip(offset).Take(batchSize).Select(format).ToArray();
            await writer.WriteLineAsync();
            await writer.WriteLineAsync($"INSERT INTO {table} ({columns}) VALUES");
            await writer.WriteLineAsync(string.Join(",\n", batch));
            await writer.WriteLineAsync(";");
        }
    }

    private static string SqlString(string? value)
    {
        if (value == null)
            return "NULL";

        var escaped = value
            .Replace("'", "''")
            .Replace("$(", "' + NCHAR(36) + N'(");
        return $"N'{escaped}'";
    }

    private static string SqlGuid(Guid value) => $"'{value:D}'";
    private static string SqlGuid(Guid? value) => value.HasValue ? SqlGuid(value.Value) : "NULL";
    private static string SqlInt(int? value) => value?.ToString() ?? "NULL";
    private static string SqlBool(bool value) => value ? "1" : "0";
    private static string SqlDateTime(DateTimeOffset value) => $"'{value.UtcDateTime:yyyy-MM-ddTHH:mm:ss.fffffffZ}'";

    private const string SchemaSql = """
-- SQL Server schema for the versioned source-reference index.
SET NOCOUNT ON;

IF OBJECT_ID(N'OI_Applications', N'U') IS NULL
BEGIN
    CREATE TABLE OI_Applications
    (
        ApplicationId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
        Name NVARCHAR(300) NOT NULL
    );
END;

IF OBJECT_ID(N'OI_Builds', N'U') IS NULL
BEGIN
    CREATE TABLE OI_Builds
    (
        BuildId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
        ApplicationId UNIQUEIDENTIFIER NOT NULL,
        Version NVARCHAR(200) NOT NULL,
        CommitSha NVARCHAR(100) NULL,
        SourceSolution NVARCHAR(2000) NOT NULL,
        GeneratedAtUtc DATETIME2(7) NOT NULL
    );
END;

IF OBJECT_ID(N'OI_Projects', N'U') IS NULL
BEGIN
    CREATE TABLE OI_Projects
    (
        ProjectId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
        BuildId UNIQUEIDENTIFIER NOT NULL,
        Name NVARCHAR(500) NOT NULL,
        AssemblyName NVARCHAR(500) NULL,
        ProjectPath NVARCHAR(2000) NULL,
        IsSeedProject BIT NOT NULL
    );
END;

IF OBJECT_ID(N'OI_Files', N'U') IS NULL
BEGIN
    CREATE TABLE OI_Files
    (
        FileId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
        BuildId UNIQUEIDENTIFIER NOT NULL,
        ProjectId UNIQUEIDENTIFIER NOT NULL,
        RelativePath NVARCHAR(2000) NOT NULL,
        HashSha256 CHAR(64) NOT NULL
    );
END;

IF OBJECT_ID(N'OI_Symbols', N'U') IS NULL
BEGIN
    CREATE TABLE OI_Symbols
    (
        SymbolId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
        BuildId UNIQUEIDENTIFIER NOT NULL,
        ProjectId UNIQUEIDENTIFIER NOT NULL,
        ContainingSymbolId UNIQUEIDENTIFIER NULL,
        Kind NVARCHAR(40) NOT NULL,
        Name NVARCHAR(500) NOT NULL,
        QualifiedName NVARCHAR(MAX) NOT NULL,
        SymbolKey NVARCHAR(MAX) NOT NULL
    );
END;

IF OBJECT_ID(N'OI_Declarations', N'U') IS NULL
BEGIN
    CREATE TABLE OI_Declarations
    (
        DeclarationId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
        BuildId UNIQUEIDENTIFIER NOT NULL,
        SymbolId UNIQUEIDENTIFIER NOT NULL,
        FileId UNIQUEIDENTIFIER NOT NULL,
        StartLine INT NOT NULL,
        StartColumn INT NOT NULL,
        EndLine INT NOT NULL,
        EndColumn INT NOT NULL
    );
END;

IF OBJECT_ID(N'OI_FieldReferences', N'U') IS NULL
BEGIN
    CREATE TABLE OI_FieldReferences
    (
        FieldReferenceId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
        BuildId UNIQUEIDENTIFIER NOT NULL,
        FieldSymbolId UNIQUEIDENTIFIER NOT NULL,
        ContainingFunctionId UNIQUEIDENTIFIER NULL,
        FileId UNIQUEIDENTIFIER NOT NULL,
        AccessKind NVARCHAR(20) NOT NULL,
        Line INT NOT NULL,
        ColumnNumber INT NOT NULL,
        ResolutionKind NVARCHAR(50) NOT NULL
    );
END;

IF OBJECT_ID(N'OI_ClassInstantiations', N'U') IS NULL
BEGIN
    CREATE TABLE OI_ClassInstantiations
    (
        InstantiationId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
        BuildId UNIQUEIDENTIFIER NOT NULL,
        ClassSymbolId UNIQUEIDENTIFIER NOT NULL,
        ConstructorSymbolId UNIQUEIDENTIFIER NULL,
        ContainingFunctionId UNIQUEIDENTIFIER NULL,
        FileId UNIQUEIDENTIFIER NOT NULL,
        Line INT NOT NULL,
        ColumnNumber INT NOT NULL,
        ResolutionKind NVARCHAR(50) NOT NULL
    );
END;

IF OBJECT_ID(N'OI_FunctionCalls', N'U') IS NULL
BEGIN
    CREATE TABLE OI_FunctionCalls
    (
        FunctionCallId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
        BuildId UNIQUEIDENTIFIER NOT NULL,
        CallerFunctionId UNIQUEIDENTIFIER NOT NULL,
        CalledFunctionId UNIQUEIDENTIFIER NOT NULL,
        FileId UNIQUEIDENTIFIER NULL,
        Line INT NULL,
        ColumnNumber INT NULL,
        ResolutionKind NVARCHAR(50) NOT NULL
    );
END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_OI_Builds_Application_Version')
    CREATE INDEX IX_OI_Builds_Application_Version ON OI_Builds(ApplicationId, Version);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_OI_Files_Build_Project')
    CREATE INDEX IX_OI_Files_Build_Project ON OI_Files(BuildId, ProjectId);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_OI_Symbols_Build_Kind_Name')
    CREATE INDEX IX_OI_Symbols_Build_Kind_Name ON OI_Symbols(BuildId, Kind, Name);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_OI_Declarations_Symbol')
    CREATE INDEX IX_OI_Declarations_Symbol ON OI_Declarations(BuildId, SymbolId);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_OI_FieldReferences_Field_Access')
    CREATE INDEX IX_OI_FieldReferences_Field_Access ON OI_FieldReferences(BuildId, FieldSymbolId, AccessKind);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_OI_ClassInstantiations_Class')
    CREATE INDEX IX_OI_ClassInstantiations_Class ON OI_ClassInstantiations(BuildId, ClassSymbolId);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_OI_FunctionCalls_Called')
    CREATE INDEX IX_OI_FunctionCalls_Called ON OI_FunctionCalls(BuildId, CalledFunctionId);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_OI_FunctionCalls_Caller')
    CREATE INDEX IX_OI_FunctionCalls_Caller ON OI_FunctionCalls(BuildId, CallerFunctionId);
""";

    private const string ExtensionSchemaSql = """
IF COL_LENGTH(N'OI_Applications', N'SystemType') IS NULL
    ALTER TABLE OI_Applications ADD SystemType NVARCHAR(30) NOT NULL CONSTRAINT DF_OI_Applications_SystemType_Script DEFAULT N'LEGACY';
IF COL_LENGTH(N'OI_Builds', N'ManifestHashSha256') IS NULL
    ALTER TABLE OI_Builds ADD ManifestHashSha256 CHAR(64) NULL;
IF COL_LENGTH(N'OI_Projects', N'SourceDirectory') IS NULL
    ALTER TABLE OI_Projects ADD SourceDirectory NVARCHAR(2000) NULL;
IF COL_LENGTH(N'OI_Files', N'ArtifactKind') IS NULL
    ALTER TABLE OI_Files ADD ArtifactKind NVARCHAR(80) NOT NULL CONSTRAINT DF_OI_Files_ArtifactKind_Script DEFAULT N'UNKNOWN';
IF COL_LENGTH(N'OI_Files', N'SourceRole') IS NULL
    ALTER TABLE OI_Files ADD SourceRole NVARCHAR(80) NOT NULL CONSTRAINT DF_OI_Files_SourceRole_Script DEFAULT N'APPLICATION_SOURCE';
IF COL_LENGTH(N'OI_Files', N'Ownership') IS NULL
    ALTER TABLE OI_Files ADD Ownership NVARCHAR(40) NOT NULL CONSTRAINT DF_OI_Files_Ownership_Script DEFAULT N'UNKNOWN';
IF COL_LENGTH(N'OI_Files', N'Editable') IS NULL
    ALTER TABLE OI_Files ADD Editable BIT NOT NULL CONSTRAINT DF_OI_Files_Editable_Script DEFAULT 1;
IF COL_LENGTH(N'OI_Files', N'SourceOfTruth') IS NULL
    ALTER TABLE OI_Files ADD SourceOfTruth NVARCHAR(2000) NOT NULL CONSTRAINT DF_OI_Files_SourceOfTruth_Script DEFAULT N'THIS_FILE';
IF OBJECT_ID(N'OI_SourceContents', N'U') IS NULL
BEGIN
    CREATE TABLE OI_SourceContents
    (
        HashSha256 CHAR(64) NOT NULL PRIMARY KEY,
        Compression NVARCHAR(20) NOT NULL,
        Content VARBINARY(MAX) NOT NULL,
        OriginalByteLength INT NOT NULL,
        StoredByteLength INT NOT NULL,
        CreatedAtUtc DATETIME2(7) NOT NULL
    );
END;
IF OBJECT_ID(N'OI_TextReferences', N'U') IS NULL
BEGIN
    CREATE TABLE OI_TextReferences
    (
        TextReferenceId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
        BuildId UNIQUEIDENTIFIER NOT NULL,
        FileId UNIQUEIDENTIFIER NOT NULL,
        Token NVARCHAR(200) NOT NULL,
        ReferenceKind NVARCHAR(50) NOT NULL,
        Line INT NOT NULL,
        ColumnNumber INT NOT NULL,
        ContextSnippet NVARCHAR(500) NOT NULL
    );
END;
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_OI_TextReferences_Build_Token' AND object_id = OBJECT_ID(N'OI_TextReferences'))
    CREATE INDEX IX_OI_TextReferences_Build_Token
        ON OI_TextReferences(BuildId, Token)
        INCLUDE (FileId, ReferenceKind, Line, ColumnNumber);
IF OBJECT_ID(N'OI_GitRepositories', N'U') IS NULL
BEGIN
    CREATE TABLE OI_GitRepositories
    (
        RepositoryId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
        ApplicationId UNIQUEIDENTIFIER NOT NULL,
        RootPath NVARCHAR(2000) NOT NULL,
        RemoteUrl NVARCHAR(2000) NULL,
        LastImportedCommitSha CHAR(40) NULL,
        UpdatedAtUtc DATETIME2(7) NOT NULL
    );
END;
IF OBJECT_ID(N'OI_GitCommits', N'U') IS NULL
BEGIN
    CREATE TABLE OI_GitCommits
    (
        CommitId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
        RepositoryId UNIQUEIDENTIFIER NOT NULL,
        CommitSha CHAR(40) NOT NULL,
        ParentShas NVARCHAR(500) NULL,
        AuthorName NVARCHAR(500) NULL,
        AuthorEmail NVARCHAR(500) NULL,
        CommittedAtUtc DATETIME2(7) NOT NULL,
        Message NVARCHAR(MAX) NULL
    );
END;
IF OBJECT_ID(N'OI_GitFileChanges', N'U') IS NULL
BEGIN
    CREATE TABLE OI_GitFileChanges
    (
        ChangeId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
        CommitId UNIQUEIDENTIFIER NOT NULL,
        ChangeType NVARCHAR(20) NOT NULL,
        OldPath NVARCHAR(2000) NULL,
        NewPath NVARCHAR(2000) NULL,
        Additions INT NULL,
        Deletions INT NULL,
        PatchCompression NVARCHAR(20) NULL,
        Patch VARBINARY(MAX) NULL
    );
END;
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_OI_GitCommits_Repository_Sha' AND object_id = OBJECT_ID(N'OI_GitCommits'))
    CREATE UNIQUE INDEX UX_OI_GitCommits_Repository_Sha ON OI_GitCommits(RepositoryId, CommitSha);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_OI_GitFileChanges_NewPath' AND object_id = OBJECT_ID(N'OI_GitFileChanges'))
    CREATE INDEX IX_OI_GitFileChanges_NewPath ON OI_GitFileChanges(NewPath, CommitId);
""";

    private const string FieldQuerySql = """
-- Adjust only these values.
DECLARE @ApplicationName NVARCHAR(300) = __APPLICATION__;
DECLARE @Version NVARCHAR(200) = __VERSION__;
DECLARE @FieldQualifiedName NVARCHAR(2000) = __SYMBOL__;
DECLARE @IncludeSameName BIT = 1;

DECLARE @BuildId UNIQUEIDENTIFIER;
SELECT TOP (1) @BuildId = b.BuildId
FROM OI_Builds b
JOIN OI_Applications a ON a.ApplicationId = b.ApplicationId
WHERE a.Name = @ApplicationName AND b.Version = @Version
ORDER BY b.GeneratedAtUtc DESC;

IF @BuildId IS NULL THROW 51000, 'Build not found.', 1;

DECLARE @FieldName NVARCHAR(500) = RIGHT(@FieldQualifiedName, CHARINDEX('.', REVERSE(@FieldQualifiedName) + '.') - 1);
CREATE TABLE #TargetFields (SymbolId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, MatchKind NVARCHAR(30) NOT NULL);

INSERT INTO #TargetFields
SELECT SymbolId, N'EXACT_SYMBOL'
FROM OI_Symbols
WHERE BuildId = @BuildId
  AND Kind IN (N'FIELD', N'PROPERTY')
  AND QualifiedName = @FieldQualifiedName;

IF @IncludeSameName = 1
BEGIN
    INSERT INTO #TargetFields
    SELECT s.SymbolId, N'SAME_NAME_CANDIDATE'
    FROM OI_Symbols s
    WHERE s.BuildId = @BuildId
      AND s.Kind IN (N'FIELD', N'PROPERTY')
      AND s.Name = @FieldName
      AND NOT EXISTS (SELECT 1 FROM #TargetFields t WHERE t.SymbolId = s.SymbolId);
END;

SELECT t.MatchKind, s.Kind, s.QualifiedName, f.RelativePath, d.StartLine, d.EndLine
FROM #TargetFields t
JOIN OI_Symbols s ON s.SymbolId = t.SymbolId
LEFT JOIN OI_Declarations d ON d.BuildId = @BuildId AND d.SymbolId = s.SymbolId
LEFT JOIN OI_Files f ON f.FileId = d.FileId
ORDER BY t.MatchKind, s.QualifiedName, f.RelativePath, d.StartLine;

SELECT t.MatchKind, s.QualifiedName AS FieldName, r.AccessKind, f.RelativePath, r.Line, r.ColumnNumber,
       owner.QualifiedName AS ContainingFunction
FROM #TargetFields t
JOIN OI_Symbols s ON s.SymbolId = t.SymbolId
JOIN OI_FieldReferences r ON r.BuildId = @BuildId AND r.FieldSymbolId = t.SymbolId
JOIN OI_Files f ON f.FileId = r.FileId
LEFT JOIN OI_Symbols owner ON owner.SymbolId = r.ContainingFunctionId
ORDER BY t.MatchKind, s.QualifiedName, r.AccessKind, f.RelativePath, r.Line;

SELECT tr.Token, tr.ReferenceKind, f.RelativePath, tr.Line, tr.ColumnNumber, tr.ContextSnippet
FROM OI_TextReferences tr
JOIN OI_Files f ON f.FileId = tr.FileId
WHERE tr.BuildId = @BuildId AND tr.Token = @FieldName
ORDER BY f.RelativePath, tr.Line, tr.ColumnNumber;

CREATE TABLE #FieldCallerChains
(
    FieldReferenceId UNIQUEIDENTIFIER NOT NULL,
    FunctionId UNIQUEIDENTIFIER NOT NULL,
    Depth INT NOT NULL,
    FunctionPath NVARCHAR(MAX) NOT NULL,
    VisitedIds VARCHAR(MAX) NOT NULL
);

;WITH CallerChain AS
(
    SELECT r.FieldReferenceId, r.ContainingFunctionId AS FunctionId, 0 AS Depth,
           CAST(fn.QualifiedName AS NVARCHAR(MAX)) AS FunctionPath,
           CAST('|' + CONVERT(VARCHAR(36), r.ContainingFunctionId) + '|' AS VARCHAR(MAX)) AS VisitedIds
    FROM OI_FieldReferences r
    JOIN #TargetFields t ON t.SymbolId = r.FieldSymbolId
    JOIN OI_Symbols fn ON fn.SymbolId = r.ContainingFunctionId
    WHERE r.BuildId = @BuildId AND r.ContainingFunctionId IS NOT NULL

    UNION ALL

    SELECT c.FieldReferenceId, fc.CallerFunctionId, c.Depth + 1,
           CAST(caller.QualifiedName + N' -> ' + c.FunctionPath AS NVARCHAR(MAX)),
           CAST(c.VisitedIds + CONVERT(VARCHAR(36), fc.CallerFunctionId) + '|' AS VARCHAR(MAX))
    FROM CallerChain c
    JOIN OI_FunctionCalls fc ON fc.BuildId = @BuildId AND fc.CalledFunctionId = c.FunctionId
    JOIN OI_Symbols caller ON caller.SymbolId = fc.CallerFunctionId
    WHERE c.Depth < 100
      AND CHARINDEX('|' + CONVERT(VARCHAR(36), fc.CallerFunctionId) + '|', c.VisitedIds) = 0
)
INSERT INTO #FieldCallerChains
SELECT FieldReferenceId, FunctionId, Depth, FunctionPath, VisitedIds
FROM CallerChain
OPTION (MAXRECURSION 32767);

SELECT r.AccessKind, directFile.RelativePath AS ReferenceFile, r.Line AS ReferenceLine,
       c.Depth, c.FunctionPath,
       CASE WHEN NOT EXISTS
       (
           SELECT 1 FROM OI_FunctionCalls parent
           WHERE parent.BuildId = @BuildId AND parent.CalledFunctionId = c.FunctionId
       ) THEN 1 ELSE 0 END AS IsRoot
FROM #FieldCallerChains c
JOIN OI_FieldReferences r ON r.FieldReferenceId = c.FieldReferenceId
JOIN OI_Files directFile ON directFile.FileId = r.FileId
ORDER BY directFile.RelativePath, r.Line, c.Depth DESC, c.FunctionPath;

;WITH RelevantFiles AS
(
    SELECT d.FileId, N'FIELD_DECLARATION' AS Reason
    FROM #TargetFields t JOIN OI_Declarations d ON d.SymbolId = t.SymbolId AND d.BuildId = @BuildId
    UNION
    SELECT r.FileId, N'FIELD_REFERENCE'
    FROM #TargetFields t JOIN OI_FieldReferences r ON r.FieldSymbolId = t.SymbolId AND r.BuildId = @BuildId
    UNION
    SELECT d.FileId, N'CALLER_CHAIN'
    FROM #FieldCallerChains c JOIN OI_Declarations d ON d.SymbolId = c.FunctionId AND d.BuildId = @BuildId
    UNION
    SELECT tr.FileId, N'TEXT_REFERENCE'
    FROM OI_TextReferences tr
    WHERE tr.BuildId = @BuildId AND tr.Token = @FieldName
)
SELECT DISTINCT f.RelativePath, rf.Reason
FROM RelevantFiles rf JOIN OI_Files f ON f.FileId = rf.FileId
ORDER BY f.RelativePath, rf.Reason;
""";

    private const string ClassQuerySql = """
-- Adjust only these values.
DECLARE @ApplicationName NVARCHAR(300) = __APPLICATION__;
DECLARE @Version NVARCHAR(200) = __VERSION__;
DECLARE @ClassQualifiedName NVARCHAR(2000) = __SYMBOL__;

DECLARE @BuildId UNIQUEIDENTIFIER;
SELECT TOP (1) @BuildId = b.BuildId
FROM OI_Builds b
JOIN OI_Applications a ON a.ApplicationId = b.ApplicationId
WHERE a.Name = @ApplicationName AND b.Version = @Version
ORDER BY b.GeneratedAtUtc DESC;

IF @BuildId IS NULL THROW 51000, 'Build not found.', 1;

DECLARE @ClassName NVARCHAR(500) = RIGHT(@ClassQualifiedName, CHARINDEX('.', REVERSE(@ClassQualifiedName) + '.') - 1);
CREATE TABLE #TargetClasses (SymbolId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY);
INSERT INTO #TargetClasses
SELECT SymbolId FROM OI_Symbols
WHERE BuildId = @BuildId
  AND Kind = N'CLASS'
  AND (QualifiedName = @ClassQualifiedName OR Name = @ClassName);

SELECT s.QualifiedName, f.RelativePath, d.StartLine, d.EndLine
FROM #TargetClasses t
JOIN OI_Symbols s ON s.SymbolId = t.SymbolId
JOIN OI_Declarations d ON d.BuildId = @BuildId AND d.SymbolId = t.SymbolId
JOIN OI_Files f ON f.FileId = d.FileId
ORDER BY f.RelativePath, d.StartLine;

SELECT s.QualifiedName, f.RelativePath, i.Line, i.ColumnNumber,
       owner.QualifiedName AS ContainingFunction
FROM #TargetClasses t
JOIN OI_Symbols s ON s.SymbolId = t.SymbolId
JOIN OI_ClassInstantiations i ON i.BuildId = @BuildId AND i.ClassSymbolId = t.SymbolId
JOIN OI_Files f ON f.FileId = i.FileId
LEFT JOIN OI_Symbols owner ON owner.SymbolId = i.ContainingFunctionId
ORDER BY f.RelativePath, i.Line;

SELECT tr.Token, tr.ReferenceKind, f.RelativePath, tr.Line, tr.ColumnNumber, tr.ContextSnippet
FROM OI_TextReferences tr
JOIN OI_Files f ON f.FileId = tr.FileId
WHERE tr.BuildId = @BuildId AND tr.Token = @ClassName
ORDER BY f.RelativePath, tr.Line, tr.ColumnNumber;

CREATE TABLE #ClassCallerChains
(
    InstantiationId UNIQUEIDENTIFIER NOT NULL,
    FunctionId UNIQUEIDENTIFIER NOT NULL,
    Depth INT NOT NULL,
    FunctionPath NVARCHAR(MAX) NOT NULL,
    VisitedIds VARCHAR(MAX) NOT NULL
);

;WITH CallerChain AS
(
    SELECT i.InstantiationId, i.ContainingFunctionId AS FunctionId, 0 AS Depth,
           CAST(fn.QualifiedName AS NVARCHAR(MAX)) AS FunctionPath,
           CAST('|' + CONVERT(VARCHAR(36), i.ContainingFunctionId) + '|' AS VARCHAR(MAX)) AS VisitedIds
    FROM OI_ClassInstantiations i
    JOIN #TargetClasses t ON t.SymbolId = i.ClassSymbolId
    JOIN OI_Symbols fn ON fn.SymbolId = i.ContainingFunctionId
    WHERE i.BuildId = @BuildId AND i.ContainingFunctionId IS NOT NULL

    UNION ALL

    SELECT c.InstantiationId, fc.CallerFunctionId, c.Depth + 1,
           CAST(caller.QualifiedName + N' -> ' + c.FunctionPath AS NVARCHAR(MAX)),
           CAST(c.VisitedIds + CONVERT(VARCHAR(36), fc.CallerFunctionId) + '|' AS VARCHAR(MAX))
    FROM CallerChain c
    JOIN OI_FunctionCalls fc ON fc.BuildId = @BuildId AND fc.CalledFunctionId = c.FunctionId
    JOIN OI_Symbols caller ON caller.SymbolId = fc.CallerFunctionId
    WHERE c.Depth < 100
      AND CHARINDEX('|' + CONVERT(VARCHAR(36), fc.CallerFunctionId) + '|', c.VisitedIds) = 0
)
INSERT INTO #ClassCallerChains
SELECT InstantiationId, FunctionId, Depth, FunctionPath, VisitedIds
FROM CallerChain
OPTION (MAXRECURSION 32767);

SELECT sourceFile.RelativePath AS InstantiationFile, i.Line AS InstantiationLine,
       c.Depth, c.FunctionPath,
       CASE WHEN NOT EXISTS
       (
           SELECT 1 FROM OI_FunctionCalls parent
           WHERE parent.BuildId = @BuildId AND parent.CalledFunctionId = c.FunctionId
       ) THEN 1 ELSE 0 END AS IsRoot
FROM #ClassCallerChains c
JOIN OI_ClassInstantiations i ON i.InstantiationId = c.InstantiationId
JOIN OI_Files sourceFile ON sourceFile.FileId = i.FileId
ORDER BY sourceFile.RelativePath, i.Line, c.Depth DESC, c.FunctionPath;

;WITH RelevantFiles AS
(
    SELECT d.FileId, N'CLASS_DECLARATION' AS Reason
    FROM #TargetClasses t JOIN OI_Declarations d ON d.SymbolId = t.SymbolId AND d.BuildId = @BuildId
    UNION
    SELECT i.FileId, N'CLASS_INSTANTIATION'
    FROM #TargetClasses t JOIN OI_ClassInstantiations i ON i.ClassSymbolId = t.SymbolId AND i.BuildId = @BuildId
    UNION
    SELECT d.FileId, N'CALLER_CHAIN'
    FROM #ClassCallerChains c JOIN OI_Declarations d ON d.SymbolId = c.FunctionId AND d.BuildId = @BuildId
    UNION
    SELECT tr.FileId, N'TEXT_REFERENCE'
    FROM OI_TextReferences tr
    WHERE tr.BuildId = @BuildId AND tr.Token = @ClassName
)
SELECT DISTINCT f.RelativePath, rf.Reason
FROM RelevantFiles rf JOIN OI_Files f ON f.FileId = rf.FileId
ORDER BY f.RelativePath, rf.Reason;
""";

    private const string FunctionQuerySql = """
-- Use the function reported by the log. Line is optional but helps disambiguate overloads and lambdas.
DECLARE @ApplicationName NVARCHAR(300) = __APPLICATION__;
DECLARE @Version NVARCHAR(200) = __VERSION__;
DECLARE @FunctionSearch NVARCHAR(2000) = __SYMBOL__;
DECLARE @FilePath NVARCHAR(2000) = NULL;
DECLARE @Line INT = NULL;

DECLARE @BuildId UNIQUEIDENTIFIER;
SELECT TOP (1) @BuildId = b.BuildId
FROM OI_Builds b
JOIN OI_Applications a ON a.ApplicationId = b.ApplicationId
WHERE a.Name = @ApplicationName AND b.Version = @Version
ORDER BY b.GeneratedAtUtc DESC;

IF @BuildId IS NULL THROW 51000, 'Build not found.', 1;

DECLARE @FunctionName NVARCHAR(500) = RIGHT(@FunctionSearch, CHARINDEX('.', REVERSE(@FunctionSearch) + '.') - 1);
CREATE TABLE #TargetFunctions (FunctionId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY);
INSERT INTO #TargetFunctions
SELECT DISTINCT s.SymbolId
FROM OI_Symbols s
LEFT JOIN OI_Declarations d ON d.BuildId = @BuildId AND d.SymbolId = s.SymbolId
LEFT JOIN OI_Files f ON f.FileId = d.FileId
WHERE s.BuildId = @BuildId
  AND s.Kind IN (N'METHOD', N'CONSTRUCTOR', N'ACCESSOR', N'LOCAL_FUNCTION', N'LAMBDA')
  AND (s.QualifiedName = @FunctionSearch OR s.Name = @FunctionName)
  AND (@FilePath IS NULL OR REPLACE(f.RelativePath, '\', '/') LIKE N'%' + REPLACE(@FilePath, '\', '/') + N'%')
  AND (@Line IS NULL OR @Line BETWEEN d.StartLine AND d.EndLine);

CREATE TABLE #FunctionClosure
(
    DirectionName NVARCHAR(20) NOT NULL,
    FunctionId UNIQUEIDENTIFIER NOT NULL,
    Depth INT NOT NULL,
    FunctionPath NVARCHAR(MAX) NOT NULL,
    VisitedIds VARCHAR(MAX) NOT NULL
);

;WITH Upstream AS
(
    SELECT t.FunctionId, 0 AS Depth, CAST(s.QualifiedName AS NVARCHAR(MAX)) AS FunctionPath,
           CAST('|' + CONVERT(VARCHAR(36), t.FunctionId) + '|' AS VARCHAR(MAX)) AS VisitedIds
    FROM #TargetFunctions t JOIN OI_Symbols s ON s.SymbolId = t.FunctionId
    UNION ALL
    SELECT fc.CallerFunctionId, u.Depth + 1,
           CAST(caller.QualifiedName + N' -> ' + u.FunctionPath AS NVARCHAR(MAX)),
           CAST(u.VisitedIds + CONVERT(VARCHAR(36), fc.CallerFunctionId) + '|' AS VARCHAR(MAX))
    FROM Upstream u
    JOIN OI_FunctionCalls fc ON fc.BuildId = @BuildId AND fc.CalledFunctionId = u.FunctionId
    JOIN OI_Symbols caller ON caller.SymbolId = fc.CallerFunctionId
    WHERE u.Depth < 100
      AND CHARINDEX('|' + CONVERT(VARCHAR(36), fc.CallerFunctionId) + '|', u.VisitedIds) = 0
)
INSERT INTO #FunctionClosure
SELECT N'UPSTREAM', FunctionId, Depth, FunctionPath, VisitedIds FROM Upstream
OPTION (MAXRECURSION 32767);

;WITH Downstream AS
(
    SELECT t.FunctionId, 0 AS Depth, CAST(s.QualifiedName AS NVARCHAR(MAX)) AS FunctionPath,
           CAST('|' + CONVERT(VARCHAR(36), t.FunctionId) + '|' AS VARCHAR(MAX)) AS VisitedIds
    FROM #TargetFunctions t JOIN OI_Symbols s ON s.SymbolId = t.FunctionId
    UNION ALL
    SELECT fc.CalledFunctionId, d.Depth + 1,
           CAST(d.FunctionPath + N' -> ' + called.QualifiedName AS NVARCHAR(MAX)),
           CAST(d.VisitedIds + CONVERT(VARCHAR(36), fc.CalledFunctionId) + '|' AS VARCHAR(MAX))
    FROM Downstream d
    JOIN OI_FunctionCalls fc ON fc.BuildId = @BuildId AND fc.CallerFunctionId = d.FunctionId
    JOIN OI_Symbols called ON called.SymbolId = fc.CalledFunctionId
    WHERE d.Depth < 100
      AND CHARINDEX('|' + CONVERT(VARCHAR(36), fc.CalledFunctionId) + '|', d.VisitedIds) = 0
)
INSERT INTO #FunctionClosure
SELECT N'DOWNSTREAM', FunctionId, Depth, FunctionPath, VisitedIds FROM Downstream
OPTION (MAXRECURSION 32767);

SELECT DirectionName, Depth, FunctionPath
FROM #FunctionClosure
ORDER BY DirectionName, Depth, FunctionPath;

SELECT DISTINCT f.RelativePath AS RelativePath, c.DirectionName AS DirectionName
FROM #FunctionClosure c
JOIN OI_Declarations d ON d.BuildId = @BuildId AND d.SymbolId = c.FunctionId
JOIN OI_Files f ON f.FileId = d.FileId
UNION
SELECT DISTINCT f.RelativePath, N'TEXT_REFERENCE'
FROM OI_TextReferences tr
JOIN OI_Files f ON f.FileId = tr.FileId
WHERE tr.BuildId = @BuildId AND tr.Token = @FunctionName
ORDER BY RelativePath, DirectionName;
""";
}
