// <yeshua>
// artifact: GENERATED_REGENERABLE
// createdBy: DSL
// ownership: ENGINE
// editable: false
// regeneration: REPLACE
// sourceOfTruth: DSL_OR_ENGINE_TEMPLATE
// generator: Dominio.Schemas.CQRS.SourceCodeAplicationRepositoryInterfacesReadMigration
// </yeshua>

using Repositorio.Outputs;
using RepositoryInterfaces.Patterns.Command;
using RepositoryInterfaces.Patterns.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace IRepository.Read
{
    public partial interface IMaquinaReadRepository
    {
        public DataPagination<MaquinaDTO> getMaquina(ICommandRead command );
        public IEnumerable<MaquinaTenantIDDTO> getMaquinaReadFKTenantID(object command );
        public IEnumerable<MaquinaUserIdDTO> getMaquinaReadFKUserId(object command );
        public IEnumerable<MaquinaCAL_IDDTO> getMaquinaReadFKCAL_ID(object command );
        public bool ExistsById(string value );
        public bool ExistsByDescricao(string value );
        public bool ExistsByStatus(string value );
        public bool ExistsByTenantID(int value );
        public bool ExistsByDeleted(bool value );
        public bool ExistsByChanged(DateTime value );
        public bool ExistsByUserId(int value );
        public bool ExistsByCAL_ID(int value );
        public bool ExistsByMAQ_CONTROL_IP(string value );
        public bool ExistsByGMA_ID(string value );
        public bool ExistsByMAQ_ULTIMA_ATUALIZACAO(DateTime value );
        public bool ExistsByMAQ_SIRENE_SEMAFORO(int value );
        public bool ExistsByMAQ_COR_SEMAFORO(string value );
        public bool ExistsByMAQ_ID_MAQ_PAI(string value );
        public bool ExistsByMAQ_TIPO_CONTADOR(int value );
        public bool ExistsByMAQ_TIPO_PLANEJAMENTO(string value );
        public bool ExistsByMAQ_AVALIA_CUSTO(int value );
        public bool ExistsByFPR_ID_OP_PRODUZINDO(int value );
        public bool ExistsByMAQ_CONGELA_FILA(int value );
        public bool ExistsByMAQ_TEMPO_MIN_PARADA(int value );
        public bool ExistsByMAQ_QTD_CORES(int value );
        public bool ExistsByMAQ_ID_INTEGRACAO(string value );
        public bool ExistsByMAQ_ID_INTEGRACAO_ERP(string value );
        public bool ExistsByMAQ_HIERARQUIA_SEQ_TRANSFORMACAO(Decimal value );
        public bool ExistsByEQU_ID(string value );
        public bool ExistsByMAQ_PERCENTUAL_INICIO_PASSO_ANTERIOR(Decimal value );
        public bool ExistsByMAQ_ACOMPANHA_LOTE_PILOTO(string value );
        public bool ExistsByMAQ_ID_SENSOR(int value );
        public bool ExistsByMAQ_DEBOUNCING_LOW(int value );
        public bool ExistsByMAQ_DEBOUNCING_HIGHT(int value );
        public bool ExistsByMAQ_TIPO_SINAL(int value );
        public bool ExistsByTEM_ID(int value );
        public bool ExistsByMAQ_COMPRIMENTO_CHAPA_DE(Decimal value );
        public bool ExistsByMAQ_COMPRIMENTO_CHAPA_ATE(Decimal value );
        public bool ExistsByMAQ_LARGURA_CHAPA_DE(Decimal value );
        public bool ExistsByMAQ_LARGURA_CHAPA_ATE(Decimal value );
        public bool ExistsByMAQ_COMPRIMENTO_CHAPA_DE_FACAO_SUPERIOR(Decimal value );
        public bool ExistsByMAQ_COMPRIMENTO_CHAPA_ATE_FACAO_SUPERIOR(Decimal value );
        public bool ExistsByMAQ_COMPRIMENTO_CHAPA_DE_FACAO_INFERIOR(Decimal value );
        public bool ExistsByMAQ_COMPRIMENTO_CHAPA_ATE_FACAO_INFERIOR(Decimal value );
        public bool ExistsByMAQ_COMPRIMENTO_ENTRE_VINCO_DE(Decimal value );
        public bool ExistsByMAQ_COMPRIMENTO_ENTRE_VINCO_ATE(Decimal value );
        public bool ExistsByMAQ_LARGURA_ENTRE_VINCO_DE(Decimal value );
        public bool ExistsByMAQ_LARGURA_ENTRE_VINCO_ATE(Decimal value );
        public bool ExistsByMAQ_ALTURA_ENTRE_VINCO_DE(Decimal value );
        public bool ExistsByMAQ_ALTURA_ENTRE_VINCO_ATE(Decimal value );
        public bool ExistsByMAQ_COMPRIMENTO_MAIS_LARGURA_ENTRE_VINCO_DE(Decimal value );
        public bool ExistsByMAQ_COMPRIMENTO_MAIS_LARGURA_ENTRE_VINCO_ATE(Decimal value );
        public bool ExistsByMAQ_ABA_DE(Decimal value );
        public bool ExistsByMAQ_ABA_ATE(Decimal value );
        public bool ExistsByMAQ_LAP_DE(Decimal value );
        public bool ExistsByMAQ_LAP_ATE(Decimal value );
        public bool ExistsByMAQ_ONDAS(string value );
        public bool ExistsByMAQ_PROLONGA_LAP(string value );
        public bool ExistsByMAQ_LARGURA_IMPRESSAO(Decimal value );
        public bool ExistsByMAQ_COMPRIMENTO_IMPRESSAO(Decimal value );
        public bool ExistsByMAQ_ROLO_DISPOSITIVO_DE(Decimal value );
        public bool ExistsByMAQ_ROLO_DISPOSITIVO_ATE(Decimal value );
        public bool ExistsByMAQ_FAMILIAS(string value );
        public bool ExistsByMAQ_REFILE_MINIMO(Decimal value );
        public bool ExistsByMAQ_LARGURA_UTIL(Decimal value );
        public bool ExistsByMAQ_TOTAL_ACO(Decimal value );
        public bool ExistsByMAQ_FECHAMENTO(string value );
        public bool ExistsByMAQ_OPERACAO_VINCAR(Decimal value );
        public bool ExistsByMAQ_OPERACAO_MONTA_DIVISAO(Decimal value );
        public bool ExistsByMAQ_OPERACAO_SERRAR(Decimal value );
        public bool ExistsByMAQ_TIPO_LAP(string value );
        public bool ExistsByMAQ_INDICE_PARADAS_POR_OP(Decimal value );
        public bool ExistsByMAQ_PERDA_MAXIMA(int value );
        public bool ExistsByMAQ_TOTAL_PECAS_REFILANDO(int value );
        public bool ExistsByMAQ_TOTAL_PECAS_NAO_REFILANDO(int value );
        public bool ExistsByMAQ_TOTAL_VINCOS(int value );
        public MaquinaDTO FirstById(string value );
        public MaquinaDTO FirstByDescricao(string value );
        public MaquinaDTO FirstByStatus(string value );
        public MaquinaDTO FirstByTenantID(int value );
        public MaquinaDTO FirstByDeleted(bool value );
        public MaquinaDTO FirstByChanged(DateTime value );
        public MaquinaDTO FirstByUserId(int value );
        public MaquinaDTO FirstByCAL_ID(int value );
        public MaquinaDTO FirstByMAQ_CONTROL_IP(string value );
        public MaquinaDTO FirstByGMA_ID(string value );
        public MaquinaDTO FirstByMAQ_ULTIMA_ATUALIZACAO(DateTime value );
        public MaquinaDTO FirstByMAQ_SIRENE_SEMAFORO(int value );
        public MaquinaDTO FirstByMAQ_COR_SEMAFORO(string value );
        public MaquinaDTO FirstByMAQ_ID_MAQ_PAI(string value );
        public MaquinaDTO FirstByMAQ_TIPO_CONTADOR(int value );
        public MaquinaDTO FirstByMAQ_TIPO_PLANEJAMENTO(string value );
        public MaquinaDTO FirstByMAQ_AVALIA_CUSTO(int value );
        public MaquinaDTO FirstByFPR_ID_OP_PRODUZINDO(int value );
        public MaquinaDTO FirstByMAQ_CONGELA_FILA(int value );
        public MaquinaDTO FirstByMAQ_TEMPO_MIN_PARADA(int value );
        public MaquinaDTO FirstByMAQ_QTD_CORES(int value );
        public MaquinaDTO FirstByMAQ_ID_INTEGRACAO(string value );
        public MaquinaDTO FirstByMAQ_ID_INTEGRACAO_ERP(string value );
        public MaquinaDTO FirstByMAQ_HIERARQUIA_SEQ_TRANSFORMACAO(Decimal value );
        public MaquinaDTO FirstByEQU_ID(string value );
        public MaquinaDTO FirstByMAQ_PERCENTUAL_INICIO_PASSO_ANTERIOR(Decimal value );
        public MaquinaDTO FirstByMAQ_ACOMPANHA_LOTE_PILOTO(string value );
        public MaquinaDTO FirstByMAQ_ID_SENSOR(int value );
        public MaquinaDTO FirstByMAQ_DEBOUNCING_LOW(int value );
        public MaquinaDTO FirstByMAQ_DEBOUNCING_HIGHT(int value );
        public MaquinaDTO FirstByMAQ_TIPO_SINAL(int value );
        public MaquinaDTO FirstByTEM_ID(int value );
        public MaquinaDTO FirstByMAQ_COMPRIMENTO_CHAPA_DE(Decimal value );
        public MaquinaDTO FirstByMAQ_COMPRIMENTO_CHAPA_ATE(Decimal value );
        public MaquinaDTO FirstByMAQ_LARGURA_CHAPA_DE(Decimal value );
        public MaquinaDTO FirstByMAQ_LARGURA_CHAPA_ATE(Decimal value );
        public MaquinaDTO FirstByMAQ_COMPRIMENTO_CHAPA_DE_FACAO_SUPERIOR(Decimal value );
        public MaquinaDTO FirstByMAQ_COMPRIMENTO_CHAPA_ATE_FACAO_SUPERIOR(Decimal value );
        public MaquinaDTO FirstByMAQ_COMPRIMENTO_CHAPA_DE_FACAO_INFERIOR(Decimal value );
        public MaquinaDTO FirstByMAQ_COMPRIMENTO_CHAPA_ATE_FACAO_INFERIOR(Decimal value );
        public MaquinaDTO FirstByMAQ_COMPRIMENTO_ENTRE_VINCO_DE(Decimal value );
        public MaquinaDTO FirstByMAQ_COMPRIMENTO_ENTRE_VINCO_ATE(Decimal value );
        public MaquinaDTO FirstByMAQ_LARGURA_ENTRE_VINCO_DE(Decimal value );
        public MaquinaDTO FirstByMAQ_LARGURA_ENTRE_VINCO_ATE(Decimal value );
        public MaquinaDTO FirstByMAQ_ALTURA_ENTRE_VINCO_DE(Decimal value );
        public MaquinaDTO FirstByMAQ_ALTURA_ENTRE_VINCO_ATE(Decimal value );
        public MaquinaDTO FirstByMAQ_COMPRIMENTO_MAIS_LARGURA_ENTRE_VINCO_DE(Decimal value );
        public MaquinaDTO FirstByMAQ_COMPRIMENTO_MAIS_LARGURA_ENTRE_VINCO_ATE(Decimal value );
        public MaquinaDTO FirstByMAQ_ABA_DE(Decimal value );
        public MaquinaDTO FirstByMAQ_ABA_ATE(Decimal value );
        public MaquinaDTO FirstByMAQ_LAP_DE(Decimal value );
        public MaquinaDTO FirstByMAQ_LAP_ATE(Decimal value );
        public MaquinaDTO FirstByMAQ_ONDAS(string value );
        public MaquinaDTO FirstByMAQ_PROLONGA_LAP(string value );
        public MaquinaDTO FirstByMAQ_LARGURA_IMPRESSAO(Decimal value );
        public MaquinaDTO FirstByMAQ_COMPRIMENTO_IMPRESSAO(Decimal value );
        public MaquinaDTO FirstByMAQ_ROLO_DISPOSITIVO_DE(Decimal value );
        public MaquinaDTO FirstByMAQ_ROLO_DISPOSITIVO_ATE(Decimal value );
        public MaquinaDTO FirstByMAQ_FAMILIAS(string value );
        public MaquinaDTO FirstByMAQ_REFILE_MINIMO(Decimal value );
        public MaquinaDTO FirstByMAQ_LARGURA_UTIL(Decimal value );
        public MaquinaDTO FirstByMAQ_TOTAL_ACO(Decimal value );
        public MaquinaDTO FirstByMAQ_FECHAMENTO(string value );
        public MaquinaDTO FirstByMAQ_OPERACAO_VINCAR(Decimal value );
        public MaquinaDTO FirstByMAQ_OPERACAO_MONTA_DIVISAO(Decimal value );
        public MaquinaDTO FirstByMAQ_OPERACAO_SERRAR(Decimal value );
        public MaquinaDTO FirstByMAQ_TIPO_LAP(string value );
        public MaquinaDTO FirstByMAQ_INDICE_PARADAS_POR_OP(Decimal value );
        public MaquinaDTO FirstByMAQ_PERDA_MAXIMA(int value );
        public MaquinaDTO FirstByMAQ_TOTAL_PECAS_REFILANDO(int value );
        public MaquinaDTO FirstByMAQ_TOTAL_PECAS_NAO_REFILANDO(int value );
        public MaquinaDTO FirstByMAQ_TOTAL_VINCOS(int value );
        public IEnumerable<MaquinaDTO> GetAllById(string value );
        public IEnumerable<MaquinaDTO> GetAllByDescricao(string value );
        public IEnumerable<MaquinaDTO> GetAllByStatus(string value );
        public IEnumerable<MaquinaDTO> GetAllByTenantID(int value );
        public IEnumerable<MaquinaDTO> GetAllByDeleted(bool value );
        public IEnumerable<MaquinaDTO> GetAllByChanged(DateTime value );
        public IEnumerable<MaquinaDTO> GetAllByUserId(int value );
        public IEnumerable<MaquinaDTO> GetAllByCAL_ID(int value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_CONTROL_IP(string value );
        public IEnumerable<MaquinaDTO> GetAllByGMA_ID(string value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_ULTIMA_ATUALIZACAO(DateTime value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_SIRENE_SEMAFORO(int value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_COR_SEMAFORO(string value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_ID_MAQ_PAI(string value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_TIPO_CONTADOR(int value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_TIPO_PLANEJAMENTO(string value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_AVALIA_CUSTO(int value );
        public IEnumerable<MaquinaDTO> GetAllByFPR_ID_OP_PRODUZINDO(int value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_CONGELA_FILA(int value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_TEMPO_MIN_PARADA(int value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_QTD_CORES(int value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_ID_INTEGRACAO(string value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_ID_INTEGRACAO_ERP(string value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_HIERARQUIA_SEQ_TRANSFORMACAO(Decimal value );
        public IEnumerable<MaquinaDTO> GetAllByEQU_ID(string value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_PERCENTUAL_INICIO_PASSO_ANTERIOR(Decimal value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_ACOMPANHA_LOTE_PILOTO(string value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_ID_SENSOR(int value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_DEBOUNCING_LOW(int value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_DEBOUNCING_HIGHT(int value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_TIPO_SINAL(int value );
        public IEnumerable<MaquinaDTO> GetAllByTEM_ID(int value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_COMPRIMENTO_CHAPA_DE(Decimal value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_COMPRIMENTO_CHAPA_ATE(Decimal value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_LARGURA_CHAPA_DE(Decimal value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_LARGURA_CHAPA_ATE(Decimal value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_COMPRIMENTO_CHAPA_DE_FACAO_SUPERIOR(Decimal value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_COMPRIMENTO_CHAPA_ATE_FACAO_SUPERIOR(Decimal value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_COMPRIMENTO_CHAPA_DE_FACAO_INFERIOR(Decimal value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_COMPRIMENTO_CHAPA_ATE_FACAO_INFERIOR(Decimal value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_COMPRIMENTO_ENTRE_VINCO_DE(Decimal value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_COMPRIMENTO_ENTRE_VINCO_ATE(Decimal value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_LARGURA_ENTRE_VINCO_DE(Decimal value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_LARGURA_ENTRE_VINCO_ATE(Decimal value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_ALTURA_ENTRE_VINCO_DE(Decimal value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_ALTURA_ENTRE_VINCO_ATE(Decimal value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_COMPRIMENTO_MAIS_LARGURA_ENTRE_VINCO_DE(Decimal value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_COMPRIMENTO_MAIS_LARGURA_ENTRE_VINCO_ATE(Decimal value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_ABA_DE(Decimal value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_ABA_ATE(Decimal value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_LAP_DE(Decimal value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_LAP_ATE(Decimal value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_ONDAS(string value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_PROLONGA_LAP(string value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_LARGURA_IMPRESSAO(Decimal value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_COMPRIMENTO_IMPRESSAO(Decimal value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_ROLO_DISPOSITIVO_DE(Decimal value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_ROLO_DISPOSITIVO_ATE(Decimal value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_FAMILIAS(string value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_REFILE_MINIMO(Decimal value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_LARGURA_UTIL(Decimal value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_TOTAL_ACO(Decimal value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_FECHAMENTO(string value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_OPERACAO_VINCAR(Decimal value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_OPERACAO_MONTA_DIVISAO(Decimal value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_OPERACAO_SERRAR(Decimal value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_TIPO_LAP(string value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_INDICE_PARADAS_POR_OP(Decimal value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_PERDA_MAXIMA(int value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_TOTAL_PECAS_REFILANDO(int value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_TOTAL_PECAS_NAO_REFILANDO(int value );
        public IEnumerable<MaquinaDTO> GetAllByMAQ_TOTAL_VINCOS(int value );
    }
}
//Dominio.Schemas.CQRS.SourceCodeAplicationRepositoryInterfacesReadMigration