map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}

# generated: Dominio.Deployment.DockerComposeRenderer
server {
    listen 80;
    server_name playsis.com.br;
    resolver 127.0.0.11 ipv6=off valid=30s;

    location /volatile/ {
        alias /storage/volatile/;
    }

    location /mdfe/yapi {
        set $fiscal_mdfe_api_upstream fiscal-mdfe-api:7214;
        rewrite ^/mdfe/yapi(?:/(.*))?$ /yapi/$1 break;
        proxy_pass http://$fiscal_mdfe_api_upstream;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }

    location /yworker {
        set $clinica_worker_upstream clinica-worker:7215;
        proxy_pass http://$clinica_worker_upstream;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }

    location /mdfe {
        set $fiscal_mdfe_front_upstream fiscal-mdfe-front:8080;
        rewrite ^/mdfe(?:/(.*))?$ /$1 break;
        proxy_pass http://$fiscal_mdfe_front_upstream;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }

    location /yapi {
        set $clinica_api_upstream clinica-api:7214;
        proxy_pass http://$clinica_api_upstream;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }

    location / {
        set $clinica_front_upstream clinica-front:8080;
        proxy_pass http://$clinica_front_upstream;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }
}
