<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <InvariantGlobalization>false</InvariantGlobalization>
    <YeshuaCommitSha Condition="'$(YeshuaCommitSha)' == ''">$(SourceRevisionId)</YeshuaCommitSha>
    <YeshuaBuildTimestampUtc Condition="'$(YeshuaBuildTimestampUtc)' == ''">UNSET</YeshuaBuildTimestampUtc>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Yeshua.APS.ADM.CQRS.Infrastructure.Shared\Yeshua.APS.ADM.CQRS.Infrastructure.Shared.csproj" />
    <ProjectReference Include="..\..\Domain\Yeshua.APS.ADM.CQRS.Domain\Yeshua.APS.ADM.CQRS.Domain.csproj" />
    <ProjectReference Include="..\..\Application\Yeshua.APS.ADM.CQRS.Application.Command\Yeshua.APS.ADM.CQRS.Application.Command.csproj" />
    <ProjectReference Include="..\..\Application\Yeshua.APS.ADM.CQRS.Application.RepositoryInterfaces\Yeshua.APS.ADM.CQRS.Application.RepositoryInterfaces.csproj" />
    <ProjectReference Include="..\Yeshua.APS.ADM.CQRS.Infrastructure.RepositoryRead\Yeshua.APS.ADM.CQRS.Infrastructure.RepositoryRead.csproj" />
    <ProjectReference Include="..\Yeshua.APS.ADM.CQRS.Infrastructure.RepositoryWrite\Yeshua.APS.ADM.CQRS.Infrastructure.RepositoryWrite.csproj" />
  </ItemGroup>
  <ItemGroup>
    <RuntimeHostConfigurationOption Include="Yeshua.Application" Value="APS.ADM" />
    <RuntimeHostConfigurationOption Include="Yeshua.Version" Value="$(Version)" />
    <RuntimeHostConfigurationOption Include="Yeshua.CommitSha" Value="$(YeshuaCommitSha)" />
    <RuntimeHostConfigurationOption Include="Yeshua.BuildTimestampUtc" Value="$(YeshuaBuildTimestampUtc)" />
  </ItemGroup>
</Project>