location /volatile/ {
    alias /storage/volatile/;
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    default_type application/octet-stream;
    expires 30d;
    add_header Cache-Control "public";
}

