<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Enum\**" />
    <Compile Remove="Especificacoes\**" />
    <EmbeddedResource Remove="Enum\**" />
    <EmbeddedResource Remove="Especificacoes\**" />
    <None Remove="Enum\**" />
    <None Remove="Especificacoes\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Entitys\" />
    <Folder Include="Specification\Agenda\" />
    <Folder Include="Specification\Clinica\" />
    <Folder Include="Specification\Paciente\" />
    <Folder Include="Specification\Proficional\" />
  </ItemGroup>

</Project>
