<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Especificacoes\**" />
    <Compile Remove="Specification\**" />
    <EmbeddedResource Remove="Especificacoes\**" />
    <EmbeddedResource Remove="Specification\**" />
    <None Remove="Especificacoes\**" />
    <None Remove="Specification\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Saga\Custom\" />
    <Folder Include="Enum\" />
    <Folder Include="Saga\" />
    <Folder Include="Saga\Migration\" />
  </ItemGroup>

</Project>
