<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <InvariantGlobalization>false</InvariantGlobalization>
    <YeshuaCommitSha Condition="'$(YeshuaCommitSha)' == ''">$(SourceRevisionId)</YeshuaCommitSha>
    <YeshuaBuildTimestampUtc Condition="'$(YeshuaBuildTimestampUtc)' == ''">UNSET</YeshuaBuildTimestampUtc>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.14" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Domain\Yeshua.Clinica.CQRS.Domain\Yeshua.Clinica.CQRS.Domain.csproj" />
    <ProjectReference Include="..\..\Application\Yeshua.Clinica.CQRS.Application.Command\Yeshua.Clinica.CQRS.Application.Command.csproj" />
    <ProjectReference Include="..\..\Application\Yeshua.Clinica.CQRS.Application.RepositoryInterfaces\Yeshua.Clinica.CQRS.Application.RepositoryInterfaces.csproj" />
    <ProjectReference Include="..\Yeshua.Clinica.CQRS.Infrastructure.RepositoryRead\Yeshua.Clinica.CQRS.Infrastructure.RepositoryRead.csproj" />
    <ProjectReference Include="..\Yeshua.Clinica.CQRS.Infrastructure.RepositoryWrite\Yeshua.Clinica.CQRS.Infrastructure.RepositoryWrite.csproj" />
    <ProjectReference Include="..\Yeshua.Clinica.CQRS.Infrastructure.Shared\Yeshua.Clinica.CQRS.Infrastructure.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <AssemblyMetadata Include="YeshuaApplication" Value="Clinica" />
    <AssemblyMetadata Include="YeshuaVersion" Value="$(Version)" />
    <AssemblyMetadata Include="YeshuaCommitSha" Value="$(YeshuaCommitSha)" />
    <AssemblyMetadata Include="YeshuaBuildTimestampUtc" Value="$(YeshuaBuildTimestampUtc)" />
  </ItemGroup>
</Project>