version: "3.9"

services:
  front:
    build:
      context: ../../..
      dockerfile: Devops/infra/docker/front/Dockerfile
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:8080"
      ASPNETCORE_ENVIRONMENT: "Production"
    expose:
      - "8080"
    restart: unless-stopped
    networks:
      - yeshua-net


  nginx:
    container_name: yeshua-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - front
    restart: unless-stopped
    networks:
      - yeshua-net


networks:
  yeshua-net:
    driver: bridge
