    services:
      front:
        build:
          context: ../../..
          dockerfile: Devops/infra/docker/front/Dockerfile
        environment:
          ASPNETCORE_URLS: "http://0.0.0.0:8080"
          ASPNETCORE_ENVIRONMENT: "Production"
          SA__PASSWORD: "123qwe!@#QWE"
          MYCONFIG__READCONECTIONSTRING: "Server=sqlserver,1433;Database=CLINICA1;User Id=sa;Password=123qwe!@#QWE;TrustServerCertificate=True;"
          MYCONFIG__WRITECONECTIONSTRING: "Server=sqlserver,1433;Database=CLINICA1;User Id=sa;Password=123qwe!@#QWE;TrustServerCertificate=True;"
        expose:
          - "8080"
        restart: unless-stopped
        networks:
          - yeshua-net

      api:
        build:
          context: ../../..
          dockerfile: Devops/infra/docker/api/Dockerfile
        environment:
          ASPNETCORE_URLS: "http://0.0.0.0:7214"
          ASPNETCORE_ENVIRONMENT: "Production"
          ConnectionStrings__Default: "Server=sqlserver,1433;Database=CLINICA1;User Id=sa;Password=123qwe!@#QWE;TrustServerCertificate=True;"
          Redis__Host: redis
          SA__PASSWORD: "123qwe!@#QWE"
          MYCONFIG__READCONECTIONSTRING: "Server=sqlserver,1433;Database=CLINICA1;User Id=sa;Password=123qwe!@#QWE;TrustServerCertificate=True;"
          MYCONFIG__WRITECONECTIONSTRING: "Server=sqlserver,1433;Database=CLINICA1;User Id=sa;Password=123qwe!@#QWE;TrustServerCertificate=True;"
          FileSystem__RootPath: "/storage"
          FileSystem__BaseUrl: "https://playsis.com.br"
        expose:
          - "7214"
        depends_on:
          - sqlserver
          - redis
        volumes:
          - /root/YeshuaStorage:/storage
        restart: unless-stopped
        networks:
          - yeshua-net



      worker:
        build:
            context: ../../..
            dockerfile: Devops/infra/docker/worker/Dockerfile
        environment:
            ASPNETCORE_URLS: "http://0.0.0.0:7215"
            ASPNETCORE_ENVIRONMENT: "Production"

            ConnectionStrings__Default: "Server=sqlserver,1433;Database=CLINICA1;User Id=sa;Password=123qwe!@#QWE;TrustServerCertificate=True;"
            Redis__Host: redis

            MYCONFIG__READCONECTIONSTRING: "Server=sqlserver,1433;Database=CLINICA1;User Id=sa;Password=123qwe!@#QWE;TrustServerCertificate=True;"
            MYCONFIG__WRITECONECTIONSTRING: "Server=sqlserver,1433;Database=CLINICA1;User Id=sa;Password=123qwe!@#QWE;TrustServerCertificate=True;"

            FileSystem__RootPath: "/storage"
            FileSystem__BaseUrl: "https://playsis.com.br"

            RabbitMq__HostName: rabbitmq
            RabbitMq__Port: 5672
            RabbitMq__Username: yeshua
            RabbitMq__Password: yeshua123
            RabbitMq__VirtualHost: /
            RabbitMq__Exchange: kiwi.exchange
            RabbitMq__Queue: kiwi.queue
            RabbitMq__RoutingKey: kiwi.routing

        expose:
            - "7215"

        depends_on:
            - sqlserver
            - redis
            - rabbitmq
        volumes:
            - /root/YeshuaStorage:/storage
        restart: unless-stopped
        networks:
            - yeshua-net


      migration:
        build:
          context: ../../..
          dockerfile: Devops/infra/docker/migration/Dockerfile
        environment:
          ConnectionStrings__Default: "Server=sqlserver,1433;Database=CLINICA1;User Id=sa;Password=123qwe!@#QWE;TrustServerCertificate=True;"
          SA__PASSWORD: "123qwe!@#QWE"
          MYCONFIG__READCONECTIONSTRING: "Server=sqlserver,1433;Database=CLINICA1;User Id=sa;Password=123qwe!@#QWE;TrustServerCertificate=True;"
          MYCONFIG__WRITECONECTIONSTRING: "Server=sqlserver,1433;Database=CLINICA1;User Id=sa;Password=123qwe!@#QWE;TrustServerCertificate=True;"
        depends_on:
          - sqlserver
        networks:
          - yeshua-net
        restart: "no"

      nginx:
        container_name: yeshua-nginx
        build:
          context: ./nginx
          dockerfile: Dockerfile
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - /etc/letsencrypt:/etc/letsencrypt:ro
          - /root/YeshuaStorage:/storage   
        depends_on:
          - front
          - api
        restart: unless-stopped
        networks:
          - yeshua-net

      redis:
        image: redis:7-alpine
        container_name: yeshua-redis
        ports:
          - "6379:6379"
        restart: unless-stopped
        networks:
          - yeshua-net

      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: yeshua-sqlserver
        environment:
          ACCEPT_EULA: "Y"
          MSSQL_PID: "Developer"
          SA_PASSWORD: "123qwe!@#QWE"
        ports:
          - "1433:1433"
        volumes:
          - /root/YeshuaDB/persistent/sql:/var/opt/mssql
        restart: unless-stopped
        networks:
          - yeshua-net


      ai-worker:
        build:
            context: ./ai-worker
            dockerfile: Dockerfile
        depends_on:
            - rabbitmq
        environment:
            CELERY_BROKER_URL: "pyamqp://yeshua:yeshua123@rabbitmq:5672//"
            STORAGE_ROOT: "/storage"
        
            RabbitMq__HostName: rabbitmq
            RabbitMq__Port: 5672
            RabbitMq__Username: yeshua
            RabbitMq__Password: yeshua123
            RabbitMq__VirtualHost: /
            RabbitMq__Exchange: kiwi.exchange
            RabbitMq__Queue: kiwi.queue
            RabbitMq__RoutingKey: kiwi.routing
            
        volumes:
            - /root/YeshuaStorage:/storage

        restart: unless-stopped
        networks:
            - yeshua-net



      rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: yeshua-rabbitmq
        ports:
          - "5672:5672"
          - "15672:15672"
        environment:
          RABBITMQ_DEFAULT_USER: yeshua
          RABBITMQ_DEFAULT_PASS: yeshua123
        networks:
          - yeshua-net
        restart: unless-stopped
    networks:
      yeshua-net:
        driver: bridge
