services:
  front:
    build:
      context: ../../..
      dockerfile: Devops/infra/docker/front/Dockerfile
    env_file:
      - .env
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:8080"
      ASPNETCORE_ENVIRONMENT: "Production"
    expose:
      - "8080"
    restart: unless-stopped
    networks:
      - yeshua-net

  api:
    build:
      context: ../../..
      dockerfile: Devops/infra/docker/api/Dockerfile
    env_file:
      - .env
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:7214"
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__Default: ${SQLSERVER_CONNECTION}
      Redis__Host: redis
    expose:
      - "7214"
    depends_on:
      - sqlserver
      - redis
    restart: unless-stopped
    networks:
      - yeshua-net

  
  migration:
      build:
        context: ../../..
        dockerfile: Devops/infra/docker/migration/Dockerfile
      env_file:
        - .env
      environment:
        ConnectionStrings__Default: ${SQLSERVER_CONNECTION}
      depends_on:
        - sqlserver
      networks:
        - yeshua-net
      restart: "no"
    
      
  nginx:
    container_name: yeshua-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - front
      - api
    restart: unless-stopped
    networks:
      - yeshua-net





  redis:
    image: redis:7-alpine
    container_name: yeshua-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - yeshua-net

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: yeshua-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      SA_PASSWORD: "123qwe!@#QWE"
    ports:
      - "1433:1433"
    volumes:
      - /root/YeshuaDB/persistent/sql:/var/opt/mssql
    restart: unless-stopped
    networks:
      - yeshua-net


networks:
  yeshua-net:
    driver: bridge
