<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.14" />
    <PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="7.1.2" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="6.5.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="6.5.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="6.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Application\Yeshua.CQRS.Application.Command\Yeshua.CQRS.Application.Command.csproj" />
    <ProjectReference Include="..\..\Application\Yeshua.CQRS.Application.RepositoryInterfaces\Yeshua.CQRS.Application.RepositoryInterfaces.csproj" />
    <ProjectReference Include="..\..\Domain\Yeshua.CQRS.Domain\Yeshua.CQRS.Domain.csproj" />
    <ProjectReference Include="..\..\..\Engine\Yeshua.Engine\Yeshua.Engine.csproj" />
    <ProjectReference Include="..\Yeshua.CQRS.Infrastructure.RepositoryRead\Yeshua.CQRS.Infrastructure.RepositoryRead.csproj" />
    <ProjectReference Include="..\Yeshua.CQRS.Infrastructure.RepositoryWrite\Yeshua.CQRS.Infrastructure.RepositoryWrite.csproj" />
    <ProjectReference Include="..\Yeshua.CQRS.Infrastructure.Shared\Yeshua.CQRS.Infrastructure.Shared.csproj" />
  </ItemGroup>

</Project>
