<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BuildInParallel>false</BuildInParallel>
  </PropertyGroup>

  <ItemGroup>
                    <ProjectReference Include="..\Yeshua.CQRS.Application.Command\Yeshua.CQRS.Application.Command.csproj" />
                    <ProjectReference Include="..\..\Domain\Yeshua.APS.Cadastros.CQRS.Domain\Yeshua.APS.Cadastros.CQRS.Domain.csproj" />
                    <ProjectReference Include="..\Yeshua.APS.Cadastros.CQRS.Application.RepositoryInterfaces\Yeshua.APS.Cadastros.CQRS.Application.RepositoryInterfaces.csproj" />
                  </ItemGroup>

</Project>
